//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetirementTime.Resources.Common {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("RetirementTime.Resources.Common.CommonResources", typeof(CommonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string NotFound_Title {
            get {
                return ResourceManager.GetString("NotFound_Title", resourceCulture);
            }
        }
        
        public static string NotFound_Message {
            get {
                return ResourceManager.GetString("NotFound_Message", resourceCulture);
            }
        }
        
        public static string Sidebar_Brand {
            get {
                return ResourceManager.GetString("Sidebar_Brand", resourceCulture);
            }
        }
        
        public static string Sidebar_BrandSub {
            get {
                return ResourceManager.GetString("Sidebar_BrandSub", resourceCulture);
            }
        }
        
        public static string Nav_Dashboard {
            get {
                return ResourceManager.GetString("Nav_Dashboard", resourceCulture);
            }
        }
        
        public static string Nav_Introduction {
            get {
                return ResourceManager.GetString("Nav_Introduction", resourceCulture);
            }
        }
        
        public static string Nav_Onboarding {
            get {
                return ResourceManager.GetString("Nav_Onboarding", resourceCulture);
            }
        }
    }
}
