//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetirementTime.Resources.BeginnerGuide {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BeginnerGuideResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BeginnerGuideResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("RetirementTime.Resources.BeginnerGuide.BeginnerGuideResources", typeof(BeginnerGuideResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Introduction_Title {
            get {
                return ResourceManager.GetString("Introduction_Title", resourceCulture);
            }
        }
        
        public static string Introduction_Description {
            get {
                return ResourceManager.GetString("Introduction_Description", resourceCulture);
            }
        }
        
        public static string Introduction_GetStarted {
            get {
                return ResourceManager.GetString("Introduction_GetStarted", resourceCulture);
            }
        }
        
        public static string MainPage_Title {
            get {
                return ResourceManager.GetString("MainPage_Title", resourceCulture);
            }
        }
        
        public static string MainPage_Assets {
            get {
                return ResourceManager.GetString("MainPage_Assets", resourceCulture);
            }
        }
        
        public static string MainPage_Debts {
            get {
                return ResourceManager.GetString("MainPage_Debts", resourceCulture);
            }
        }
        
        public static string MainPage_Income {
            get {
                return ResourceManager.GetString("MainPage_Income", resourceCulture);
            }
        }
        
        public static string MainPage_RecurringPayments {
            get {
                return ResourceManager.GetString("MainPage_RecurringPayments", resourceCulture);
            }
        }
        
        public static string MainPage_DebtsComingSoon {
            get {
                return ResourceManager.GetString("MainPage_DebtsComingSoon", resourceCulture);
            }
        }
        
        public static string MainPage_IncomeComingSoon {
            get {
                return ResourceManager.GetString("MainPage_IncomeComingSoon", resourceCulture);
            }
        }
        
        public static string MainPage_RecurringPaymentsComingSoon {
            get {
                return ResourceManager.GetString("MainPage_RecurringPaymentsComingSoon", resourceCulture);
            }
        }
        
        public static string MainPage_Copyright {
            get {
                return ResourceManager.GetString("MainPage_Copyright", resourceCulture);
            }
        }
        
        public static string MainPage_Assets_Title {
            get {
                return ResourceManager.GetString("MainPage_Assets_Title", resourceCulture);
            }
        }
        
        public static string MainPage_Assets_StepOf {
            get {
                return ResourceManager.GetString("MainPage_Assets_StepOf", resourceCulture);
            }
        }
        
        public static string Assets_Step1_Question {
            get {
                return ResourceManager.GetString("Assets_Step1_Question", resourceCulture);
            }
        }
        
        public static string Assets_Step1_Yes {
            get {
                return ResourceManager.GetString("Assets_Step1_Yes", resourceCulture);
            }
        }
        
        public static string Assets_Step1_No {
            get {
                return ResourceManager.GetString("Assets_Step1_No", resourceCulture);
            }
        }
        
        public static string Assets_Step1_PurchasePrice {
            get {
                return ResourceManager.GetString("Assets_Step1_PurchasePrice", resourceCulture);
            }
        }
        
        public static string Assets_Step1_MonthlyMortgage {
            get {
                return ResourceManager.GetString("Assets_Step1_MonthlyMortgage", resourceCulture);
            }
        }
        
        public static string Assets_Step1_MortgageLeft {
            get {
                return ResourceManager.GetString("Assets_Step1_MortgageLeft", resourceCulture);
            }
        }
        
        public static string Assets_Step1_YearlyInsurance {
            get {
                return ResourceManager.GetString("Assets_Step1_YearlyInsurance", resourceCulture);
            }
        }
        
        public static string Assets_Step1_ElectricityCosts {
            get {
                return ResourceManager.GetString("Assets_Step1_ElectricityCosts", resourceCulture);
            }
        }
        
        public static string Assets_Step1_Optional {
            get {
                return ResourceManager.GetString("Assets_Step1_Optional", resourceCulture);
            }
        }
        
        public static string Assets_Step1_MortgageDuration {
            get {
                return ResourceManager.GetString("Assets_Step1_MortgageDuration", resourceCulture);
            }
        }
        
        public static string Assets_Step1_MortgageStartDate {
            get {
                return ResourceManager.GetString("Assets_Step1_MortgageStartDate", resourceCulture);
            }
        }
        
        public static string Assets_Step1_EstimatedValue {
            get {
                return ResourceManager.GetString("Assets_Step1_EstimatedValue", resourceCulture);
            }
        }
        
        public static string Assets_Step1_SaveContinue {
            get {
                return ResourceManager.GetString("Assets_Step1_SaveContinue", resourceCulture);
            }
        }
        
        public static string Assets_Step1_Next {
            get {
                return ResourceManager.GetString("Assets_Step1_Next", resourceCulture);
            }
        }
        
        public static string Assets_StepComingSoon {
            get {
                return ResourceManager.GetString("Assets_StepComingSoon", resourceCulture);
            }
        }
    }
}
