//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetirementTime.Resources.BeginnerGuide {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BeginnerGuideResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BeginnerGuideResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RetirementTime.Resources.BeginnerGuide.BeginnerGuideResources", typeof(BeginnerGuideResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your average monthly electricity payment?.
        /// </summary>
        public static string Assets_Step1_ElectricityCosts {
            get {
                return ResourceManager.GetString("Assets_Step1_ElectricityCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the estimated current value?.
        /// </summary>
        public static string Assets_Step1_EstimatedValue {
            get {
                return ResourceManager.GetString("Assets_Step1_EstimatedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What are your monthly mortgage payments?.
        /// </summary>
        public static string Assets_Step1_MonthlyMortgage {
            get {
                return ResourceManager.GetString("Assets_Step1_MonthlyMortgage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the mortgage duration in years?.
        /// </summary>
        public static string Assets_Step1_MortgageDuration {
            get {
                return ResourceManager.GetString("Assets_Step1_MortgageDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How much mortgage is left?.
        /// </summary>
        public static string Assets_Step1_MortgageLeft {
            get {
                return ResourceManager.GetString("Assets_Step1_MortgageLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When did your mortgage start?.
        /// </summary>
        public static string Assets_Step1_MortgageStartDate {
            get {
                return ResourceManager.GetString("Assets_Step1_MortgageStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Assets_Step1_Next {
            get {
                return ResourceManager.GetString("Assets_Step1_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Assets_Step1_No {
            get {
                return ResourceManager.GetString("Assets_Step1_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Optional).
        /// </summary>
        public static string Assets_Step1_Optional {
            get {
                return ResourceManager.GetString("Assets_Step1_Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What was the purchase price?.
        /// </summary>
        public static string Assets_Step1_PurchasePrice {
            get {
                return ResourceManager.GetString("Assets_Step1_PurchasePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you own a property that is considered your main residence?.
        /// </summary>
        public static string Assets_Step1_Question {
            get {
                return ResourceManager.GetString("Assets_Step1_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; Continue.
        /// </summary>
        public static string Assets_Step1_SaveContinue {
            get {
                return ResourceManager.GetString("Assets_Step1_SaveContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your yearly insurance cost?.
        /// </summary>
        public static string Assets_Step1_YearlyInsurance {
            get {
                return ResourceManager.GetString("Assets_Step1_YearlyInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Assets_Step1_Yes {
            get {
                return ResourceManager.GetString("Assets_Step1_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        public static string Assets_Step2_AccountName {
            get {
                return ResourceManager.GetString("Assets_Step2_AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g., My TFSA, Retirement Account.
        /// </summary>
        public static string Assets_Step2_AccountNamePlaceholder {
            get {
                return ResourceManager.GetString("Assets_Step2_AccountNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account #{0}.
        /// </summary>
        public static string Assets_Step2_AccountTitle {
            get {
                return ResourceManager.GetString("Assets_Step2_AccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What type of account is this?.
        /// </summary>
        public static string Assets_Step2_AccountTypeQuestion {
            get {
                return ResourceManager.GetString("Assets_Step2_AccountTypeQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Another Account.
        /// </summary>
        public static string Assets_Step2_AddAccount {
            get {
                return ResourceManager.GetString("Assets_Step2_AddAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Holding.
        /// </summary>
        public static string Assets_Step2_AddStock {
            get {
                return ResourceManager.GetString("Assets_Step2_AddStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Assets_Step2_AmountPlaceholder {
            get {
                return ResourceManager.GetString("Assets_Step2_AmountPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want to enter the total value of the account.
        /// </summary>
        public static string Assets_Step2_BulkAmountOption {
            get {
                return ResourceManager.GetString("Assets_Step2_BulkAmountOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This includes registered accounts like TFSA, RRSP, FHSA, RESP, as well as non-registered brokerage accounts..
        /// </summary>
        public static string Assets_Step2_Description {
            get {
                return ResourceManager.GetString("Assets_Step2_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want to enter each individual holding of the account.
        /// </summary>
        public static string Assets_Step2_IndividualStocksOption {
            get {
                return ResourceManager.GetString("Assets_Step2_IndividualStocksOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How would you like to enter the account value?.
        /// </summary>
        public static string Assets_Step2_InputTypeQuestion {
            get {
                return ResourceManager.GetString("Assets_Step2_InputTypeQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Assets_Step2_Next {
            get {
                return ResourceManager.GetString("Assets_Step2_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Assets_Step2_No {
            get {
                return ResourceManager.GetString("Assets_Step2_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have any investment accounts?.
        /// </summary>
        public static string Assets_Step2_Question {
            get {
                return ResourceManager.GetString("Assets_Step2_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Assets_Step2_Remove {
            get {
                return ResourceManager.GetString("Assets_Step2_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; Continue.
        /// </summary>
        public static string Assets_Step2_SaveContinue {
            get {
                return ResourceManager.GetString("Assets_Step2_SaveContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving....
        /// </summary>
        public static string Assets_Step2_Saving {
            get {
                return ResourceManager.GetString("Assets_Step2_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select account type....
        /// </summary>
        public static string Assets_Step2_SelectAccountType {
            get {
                return ResourceManager.GetString("Assets_Step2_SelectAccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holdings.
        /// </summary>
        public static string Assets_Step2_Stocks {
            get {
                return ResourceManager.GetString("Assets_Step2_Stocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticker (e.g., AAPL).
        /// </summary>
        public static string Assets_Step2_TickerPlaceholder {
            get {
                return ResourceManager.GetString("Assets_Step2_TickerPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Value.
        /// </summary>
        public static string Assets_Step2_TotalAmount {
            get {
                return ResourceManager.GetString("Assets_Step2_TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Assets_Step2_Yes {
            get {
                return ResourceManager.GetString("Assets_Step2_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Asset.
        /// </summary>
        public static string Assets_Step3_AddAsset {
            get {
                return ResourceManager.GetString("Assets_Step3_AddAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Name.
        /// </summary>
        public static string Assets_Step3_AssetName {
            get {
                return ResourceManager.GetString("Assets_Step3_AssetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g., Gold Coins, 2020 Tesla Model 3.
        /// </summary>
        public static string Assets_Step3_AssetNamePlaceholder {
            get {
                return ResourceManager.GetString("Assets_Step3_AssetNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset #{0}.
        /// </summary>
        public static string Assets_Step3_AssetTitle {
            get {
                return ResourceManager.GetString("Assets_Step3_AssetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Type.
        /// </summary>
        public static string Assets_Step3_AssetType {
            get {
                return ResourceManager.GetString("Assets_Step3_AssetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Value.
        /// </summary>
        public static string Assets_Step3_CurrentValue {
            get {
                return ResourceManager.GetString("Assets_Step3_CurrentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have any other valuable assets such as precious metals, vehicles, jewelry, or cryptocurrency?.
        /// </summary>
        public static string Assets_Step3_Description {
            get {
                return ResourceManager.GetString("Assets_Step3_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Assets_Step3_Loading {
            get {
                return ResourceManager.GetString("Assets_Step3_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading your assets....
        /// </summary>
        public static string Assets_Step3_LoadingMessage {
            get {
                return ResourceManager.GetString("Assets_Step3_LoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Assets_Step3_No {
            get {
                return ResourceManager.GetString("Assets_Step3_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No assets added yet. Click &quot;Add Asset&quot; to get started..
        /// </summary>
        public static string Assets_Step3_NoAssetsAdded {
            get {
                return ResourceManager.GetString("Assets_Step3_NoAssetsAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Step.
        /// </summary>
        public static string Assets_Step3_PreviousStep {
            get {
                return ResourceManager.GetString("Assets_Step3_PreviousStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Price (Optional).
        /// </summary>
        public static string Assets_Step3_PurchasePrice {
            get {
                return ResourceManager.GetString("Assets_Step3_PurchasePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What you originally paid for this asset.
        /// </summary>
        public static string Assets_Step3_PurchasePriceHelp {
            get {
                return ResourceManager.GetString("Assets_Step3_PurchasePriceHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have other assets?.
        /// </summary>
        public static string Assets_Step3_Question {
            get {
                return ResourceManager.GetString("Assets_Step3_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Assets_Step3_Remove {
            get {
                return ResourceManager.GetString("Assets_Step3_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        public static string Assets_Step3_Required {
            get {
                return ResourceManager.GetString("Assets_Step3_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; Continue.
        /// </summary>
        public static string Assets_Step3_SaveContinue {
            get {
                return ResourceManager.GetString("Assets_Step3_SaveContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select Type --.
        /// </summary>
        public static string Assets_Step3_SelectType {
            get {
                return ResourceManager.GetString("Assets_Step3_SelectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 3: Other Assets.
        /// </summary>
        public static string Assets_Step3_Title {
            get {
                return ResourceManager.GetString("Assets_Step3_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Assets_Step3_Yes {
            get {
                return ResourceManager.GetString("Assets_Step3_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Investment Property.
        /// </summary>
        public static string Assets_Step4_AddProperty {
            get {
                return ResourceManager.GetString("Assets_Step4_AddProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell us about any rental properties or investment properties you own. This includes other properties you own for yourself (Eg: Lakehouse, cottage, land)..
        /// </summary>
        public static string Assets_Step4_Description {
            get {
                return ResourceManager.GetString("Assets_Step4_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated Current Value.
        /// </summary>
        public static string Assets_Step4_EstimatedValue {
            get {
                return ResourceManager.GetString("Assets_Step4_EstimatedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Assets_Step4_Loading {
            get {
                return ResourceManager.GetString("Assets_Step4_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while we load your investment properties....
        /// </summary>
        public static string Assets_Step4_LoadingMessage {
            get {
                return ResourceManager.GetString("Assets_Step4_LoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Costs (maintenance, taxes, etc.).
        /// </summary>
        public static string Assets_Step4_MonthlyCost {
            get {
                return ResourceManager.GetString("Assets_Step4_MonthlyCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Electricity Costs.
        /// </summary>
        public static string Assets_Step4_MonthlyElectricityCosts {
            get {
                return ResourceManager.GetString("Assets_Step4_MonthlyElectricityCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Mortgage Payment.
        /// </summary>
        public static string Assets_Step4_MonthlyMortgagePayments {
            get {
                return ResourceManager.GetString("Assets_Step4_MonthlyMortgagePayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Rental Revenue.
        /// </summary>
        public static string Assets_Step4_MonthlyRevenue {
            get {
                return ResourceManager.GetString("Assets_Step4_MonthlyRevenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mortgage Duration (years).
        /// </summary>
        public static string Assets_Step4_MortgageDuration {
            get {
                return ResourceManager.GetString("Assets_Step4_MortgageDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mortgage Balance Remaining.
        /// </summary>
        public static string Assets_Step4_MortgageLeft {
            get {
                return ResourceManager.GetString("Assets_Step4_MortgageLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mortgage Start Date.
        /// </summary>
        public static string Assets_Step4_MortgageStartDate {
            get {
                return ResourceManager.GetString("Assets_Step4_MortgageStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Assets_Step4_No {
            get {
                return ResourceManager.GetString("Assets_Step4_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No investment properties added yet. Click &quot;Add Property&quot; to get started..
        /// </summary>
        public static string Assets_Step4_NoPropertiesAdded {
            get {
                return ResourceManager.GetString("Assets_Step4_NoPropertiesAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Optional).
        /// </summary>
        public static string Assets_Step4_Optional {
            get {
                return ResourceManager.GetString("Assets_Step4_Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Step.
        /// </summary>
        public static string Assets_Step4_PreviousStep {
            get {
                return ResourceManager.GetString("Assets_Step4_PreviousStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Name.
        /// </summary>
        public static string Assets_Step4_PropertyName {
            get {
                return ResourceManager.GetString("Assets_Step4_PropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g., Rental Condo Downtown.
        /// </summary>
        public static string Assets_Step4_PropertyNamePlaceholder {
            get {
                return ResourceManager.GetString("Assets_Step4_PropertyNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investment Property #{0}.
        /// </summary>
        public static string Assets_Step4_PropertyTitle {
            get {
                return ResourceManager.GetString("Assets_Step4_PropertyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Price.
        /// </summary>
        public static string Assets_Step4_PurchasePrice {
            get {
                return ResourceManager.GetString("Assets_Step4_PurchasePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you own any investment properties?.
        /// </summary>
        public static string Assets_Step4_Question {
            get {
                return ResourceManager.GetString("Assets_Step4_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Assets_Step4_Remove {
            get {
                return ResourceManager.GetString("Assets_Step4_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        public static string Assets_Step4_Required {
            get {
                return ResourceManager.GetString("Assets_Step4_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; Continue.
        /// </summary>
        public static string Assets_Step4_SaveContinue {
            get {
                return ResourceManager.GetString("Assets_Step4_SaveContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investment Properties.
        /// </summary>
        public static string Assets_Step4_Title {
            get {
                return ResourceManager.GetString("Assets_Step4_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly Insurance.
        /// </summary>
        public static string Assets_Step4_YearlyInsurance {
            get {
                return ResourceManager.GetString("Assets_Step4_YearlyInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Assets_Step4_Yes {
            get {
                return ResourceManager.GetString("Assets_Step4_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step {0} content coming soon....
        /// </summary>
        public static string Assets_StepComingSoon {
            get {
                return ResourceManager.GetString("Assets_StepComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Common_Loading {
            get {
                return ResourceManager.GetString("Common_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading your data, please wait....
        /// </summary>
        public static string Common_LoadingMessage {
            get {
                return ResourceManager.GetString("Common_LoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Debt.
        /// </summary>
        public static string Debts_Step1_AddDebt {
            get {
                return ResourceManager.GetString("Debts_Step1_AddDebt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debt Amount.
        /// </summary>
        public static string Debts_Step1_Amount {
            get {
                return ResourceManager.GetString("Debts_Step1_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debt #{0}.
        /// </summary>
        public static string Debts_Step1_DebtTitle {
            get {
                return ResourceManager.GetString("Debts_Step1_DebtTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Debt.
        /// </summary>
        public static string Debts_Step1_DebtType {
            get {
                return ResourceManager.GetString("Debts_Step1_DebtType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell us about any debts you currently have, excluding mortgages..
        /// </summary>
        public static string Debts_Step1_Description {
            get {
                return ResourceManager.GetString("Debts_Step1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest Rate.
        /// </summary>
        public static string Debts_Step1_InterestRate {
            get {
                return ResourceManager.GetString("Debts_Step1_InterestRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Debts_Step1_Loading {
            get {
                return ResourceManager.GetString("Debts_Step1_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while we load your debts....
        /// </summary>
        public static string Debts_Step1_LoadingMessage {
            get {
                return ResourceManager.GetString("Debts_Step1_LoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Payment.
        /// </summary>
        public static string Debts_Step1_MonthlyPayment {
            get {
                return ResourceManager.GetString("Debts_Step1_MonthlyPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Debts_Step1_No {
            get {
                return ResourceManager.GetString("Debts_Step1_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No debts added yet. Click &quot;Add Debt&quot; to get started..
        /// </summary>
        public static string Debts_Step1_NoDebtsAdded {
            get {
                return ResourceManager.GetString("Debts_Step1_NoDebtsAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Step.
        /// </summary>
        public static string Debts_Step1_PreviousStep {
            get {
                return ResourceManager.GetString("Debts_Step1_PreviousStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you currently have any debts (excluding mortgages)?.
        /// </summary>
        public static string Debts_Step1_Question {
            get {
                return ResourceManager.GetString("Debts_Step1_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Debts_Step1_Remove {
            get {
                return ResourceManager.GetString("Debts_Step1_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        public static string Debts_Step1_Required {
            get {
                return ResourceManager.GetString("Debts_Step1_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; Continue.
        /// </summary>
        public static string Debts_Step1_SaveContinue {
            get {
                return ResourceManager.GetString("Debts_Step1_SaveContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debts.
        /// </summary>
        public static string Debts_Step1_Title {
            get {
                return ResourceManager.GetString("Debts_Step1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Loan.
        /// </summary>
        public static string Debts_Step1_Type_Car {
            get {
                return ResourceManager.GetString("Debts_Step1_Type_Car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card.
        /// </summary>
        public static string Debts_Step1_Type_CreditCard {
            get {
                return ResourceManager.GetString("Debts_Step1_Type_CreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line of Credit.
        /// </summary>
        public static string Debts_Step1_Type_LineOfCredit {
            get {
                return ResourceManager.GetString("Debts_Step1_Type_LineOfCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Debts_Step1_Type_Other {
            get {
                return ResourceManager.GetString("Debts_Step1_Type_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Loan.
        /// </summary>
        public static string Debts_Step1_Type_PersonalLoan {
            get {
                return ResourceManager.GetString("Debts_Step1_Type_PersonalLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Debts_Step1_Yes {
            get {
                return ResourceManager.GetString("Debts_Step1_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Compensation.
        /// </summary>
        public static string Income_Step1_AddCompensation {
            get {
                return ResourceManager.GetString("Income_Step1_AddCompensation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Employment.
        /// </summary>
        public static string Income_Step1_AddEmployment {
            get {
                return ResourceManager.GetString("Income_Step1_AddEmployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Compensations.
        /// </summary>
        public static string Income_Step1_AdditionalCompensations {
            get {
                return ResourceManager.GetString("Income_Step1_AdditionalCompensations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your current annual salary?.
        /// </summary>
        public static string Income_Step1_AnnualSalary {
            get {
                return ResourceManager.GetString("Income_Step1_AnnualSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What average annual wage increase do you expect?.
        /// </summary>
        public static string Income_Step1_AverageWageIncrease {
            get {
                return ResourceManager.GetString("Income_Step1_AverageWageIncrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default is 2% (inflation rate). Adjust based on your expectations..
        /// </summary>
        public static string Income_Step1_AverageWageIncreaseHint {
            get {
                return ResourceManager.GetString("Income_Step1_AverageWageIncreaseHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the annual amount?.
        /// </summary>
        public static string Income_Step1_CompensationAmount {
            get {
                return ResourceManager.GetString("Income_Step1_CompensationAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What type of compensation is this?.
        /// </summary>
        public static string Income_Step1_CompensationName {
            get {
                return ResourceManager.GetString("Income_Step1_CompensationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. Annual bonus.
        /// </summary>
        public static string Income_Step1_CompensationNamePlaceholder {
            get {
                return ResourceManager.GetString("Income_Step1_CompensationNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s start with your employment income..
        /// </summary>
        public static string Income_Step1_Description {
            get {
                return ResourceManager.GetString("Income_Step1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your employer&apos;s name?.
        /// </summary>
        public static string Income_Step1_EmployerName {
            get {
                return ResourceManager.GetString("Income_Step1_EmployerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. Acme Corp.
        /// </summary>
        public static string Income_Step1_EmployerNamePlaceholder {
            get {
                return ResourceManager.GetString("Income_Step1_EmployerNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employment #{0}.
        /// </summary>
        public static string Income_Step1_EmploymentTitle {
            get {
                return ResourceManager.GetString("Income_Step1_EmploymentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Income_Step1_No {
            get {
                return ResourceManager.GetString("Income_Step1_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No additional compensations. Click below to add one (e.g. bonus, commission, car allowance)..
        /// </summary>
        public static string Income_Step1_NoAdditionalCompensations {
            get {
                return ResourceManager.GetString("Income_Step1_NoAdditionalCompensations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No employments added yet. Click &quot;Add Employment&quot; to get started..
        /// </summary>
        public static string Income_Step1_NoEmploymentsAdded {
            get {
                return ResourceManager.GetString("Income_Step1_NoEmploymentsAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Step.
        /// </summary>
        public static string Income_Step1_PreviousStep {
            get {
                return ResourceManager.GetString("Income_Step1_PreviousStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you currently employed (as an employee)?.
        /// </summary>
        public static string Income_Step1_Question {
            get {
                return ResourceManager.GetString("Income_Step1_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Income_Step1_Remove {
            get {
                return ResourceManager.GetString("Income_Step1_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        public static string Income_Step1_Required {
            get {
                return ResourceManager.GetString("Income_Step1_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; Continue.
        /// </summary>
        public static string Income_Step1_SaveContinue {
            get {
                return ResourceManager.GetString("Income_Step1_SaveContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: Self-employment income will be covered in the next step..
        /// </summary>
        public static string Income_Step1_SelfEmploymentNote {
            get {
                return ResourceManager.GetString("Income_Step1_SelfEmploymentNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employment Income.
        /// </summary>
        public static string Income_Step1_Title {
            get {
                return ResourceManager.GetString("Income_Step1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Income_Step1_Yes {
            get {
                return ResourceManager.GetString("Income_Step1_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self-employment income coming soon....
        /// </summary>
        public static string Income_Step2_ComingSoon {
            get {
                return ResourceManager.GetString("Income_Step2_ComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This beginner&apos;s guide will help you fill out all the informations regarding your assets, debts, income, pensions, etc. To insure that you get the most accurate results possible, please take your time to fill out all the sections as accurately as possible..
        /// </summary>
        public static string Introduction_Description {
            get {
                return ResourceManager.GetString("Introduction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get started!.
        /// </summary>
        public static string Introduction_GetStarted {
            get {
                return ResourceManager.GetString("Introduction_GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction.
        /// </summary>
        public static string Introduction_Title {
            get {
                return ResourceManager.GetString("Introduction_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets.
        /// </summary>
        public static string MainPage_Assets {
            get {
                return ResourceManager.GetString("MainPage_Assets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step {0} of 5.
        /// </summary>
        public static string MainPage_Assets_StepOf {
            get {
                return ResourceManager.GetString("MainPage_Assets_StepOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets.
        /// </summary>
        public static string MainPage_Assets_Title {
            get {
                return ResourceManager.GetString("MainPage_Assets_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2024 Blazor Beginner&apos;s Guide. All rights reserved..
        /// </summary>
        public static string MainPage_Copyright {
            get {
                return ResourceManager.GetString("MainPage_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debts.
        /// </summary>
        public static string MainPage_Debts {
            get {
                return ResourceManager.GetString("MainPage_Debts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debts section coming soon....
        /// </summary>
        public static string MainPage_DebtsComingSoon {
            get {
                return ResourceManager.GetString("MainPage_DebtsComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        public static string MainPage_Income {
            get {
                return ResourceManager.GetString("MainPage_Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income section coming soon....
        /// </summary>
        public static string MainPage_IncomeComingSoon {
            get {
                return ResourceManager.GetString("MainPage_IncomeComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring Payments.
        /// </summary>
        public static string MainPage_RecurringPayments {
            get {
                return ResourceManager.GetString("MainPage_RecurringPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring Payments section coming soon....
        /// </summary>
        public static string MainPage_RecurringPaymentsComingSoon {
            get {
                return ResourceManager.GetString("MainPage_RecurringPaymentsComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MainPage.
        /// </summary>
        public static string MainPage_Title {
            get {
                return ResourceManager.GetString("MainPage_Title", resourceCulture);
            }
        }
    }
}
