//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetirementTime.Resources.BeginnerGuide {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BeginnerGuideResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BeginnerGuideResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("RetirementTime.Resources.BeginnerGuide.BeginnerGuideResources", typeof(BeginnerGuideResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Introduction_Title {
            get {
                return ResourceManager.GetString("Introduction_Title", resourceCulture);
            }
        }
        
        public static string Introduction_Description {
            get {
                return ResourceManager.GetString("Introduction_Description", resourceCulture);
            }
        }
        
        public static string Introduction_GetStarted {
            get {
                return ResourceManager.GetString("Introduction_GetStarted", resourceCulture);
            }
        }
        
        public static string MainPage_Title {
            get {
                return ResourceManager.GetString("MainPage_Title", resourceCulture);
            }
        }
        
        public static string MainPage_Assets {
            get {
                return ResourceManager.GetString("MainPage_Assets", resourceCulture);
            }
        }
        
        public static string MainPage_Debts {
            get {
                return ResourceManager.GetString("MainPage_Debts", resourceCulture);
            }
        }
        
        public static string MainPage_Income {
            get {
                return ResourceManager.GetString("MainPage_Income", resourceCulture);
            }
        }
        
        public static string MainPage_RecurringPayments {
            get {
                return ResourceManager.GetString("MainPage_RecurringPayments", resourceCulture);
            }
        }
        
        public static string MainPage_DebtsComingSoon {
            get {
                return ResourceManager.GetString("MainPage_DebtsComingSoon", resourceCulture);
            }
        }
        
        public static string MainPage_IncomeComingSoon {
            get {
                return ResourceManager.GetString("MainPage_IncomeComingSoon", resourceCulture);
            }
        }
        
        public static string MainPage_RecurringPaymentsComingSoon {
            get {
                return ResourceManager.GetString("MainPage_RecurringPaymentsComingSoon", resourceCulture);
            }
        }
        
        public static string MainPage_Copyright {
            get {
                return ResourceManager.GetString("MainPage_Copyright", resourceCulture);
            }
        }
        
        public static string MainPage_Assets_Title {
            get {
                return ResourceManager.GetString("MainPage_Assets_Title", resourceCulture);
            }
        }
        
        public static string MainPage_Assets_StepOf {
            get {
                return ResourceManager.GetString("MainPage_Assets_StepOf", resourceCulture);
            }
        }
        
        public static string Assets_Step1_Question {
            get {
                return ResourceManager.GetString("Assets_Step1_Question", resourceCulture);
            }
        }
        
        public static string Assets_Step1_Yes {
            get {
                return ResourceManager.GetString("Assets_Step1_Yes", resourceCulture);
            }
        }
        
        public static string Assets_Step1_No {
            get {
                return ResourceManager.GetString("Assets_Step1_No", resourceCulture);
            }
        }
        
        public static string Assets_Step1_PurchasePrice {
            get {
                return ResourceManager.GetString("Assets_Step1_PurchasePrice", resourceCulture);
            }
        }
        
        public static string Assets_Step1_MonthlyMortgage {
            get {
                return ResourceManager.GetString("Assets_Step1_MonthlyMortgage", resourceCulture);
            }
        }
        
        public static string Assets_Step1_MortgageLeft {
            get {
                return ResourceManager.GetString("Assets_Step1_MortgageLeft", resourceCulture);
            }
        }
        
        public static string Assets_Step1_YearlyInsurance {
            get {
                return ResourceManager.GetString("Assets_Step1_YearlyInsurance", resourceCulture);
            }
        }
        
        public static string Assets_Step1_ElectricityCosts {
            get {
                return ResourceManager.GetString("Assets_Step1_ElectricityCosts", resourceCulture);
            }
        }
        
        public static string Assets_Step1_Optional {
            get {
                return ResourceManager.GetString("Assets_Step1_Optional", resourceCulture);
            }
        }
        
        public static string Assets_Step1_MortgageDuration {
            get {
                return ResourceManager.GetString("Assets_Step1_MortgageDuration", resourceCulture);
            }
        }
        
        public static string Assets_Step1_MortgageStartDate {
            get {
                return ResourceManager.GetString("Assets_Step1_MortgageStartDate", resourceCulture);
            }
        }
        
        public static string Assets_Step1_EstimatedValue {
            get {
                return ResourceManager.GetString("Assets_Step1_EstimatedValue", resourceCulture);
            }
        }
        
        public static string Assets_Step1_SaveContinue {
            get {
                return ResourceManager.GetString("Assets_Step1_SaveContinue", resourceCulture);
            }
        }
        
        public static string Assets_Step1_Next {
            get {
                return ResourceManager.GetString("Assets_Step1_Next", resourceCulture);
            }
        }
        
        public static string Assets_Step2_Question {
            get {
                return ResourceManager.GetString("Assets_Step2_Question", resourceCulture);
            }
        }
        
        public static string Assets_Step2_Description {
            get {
                return ResourceManager.GetString("Assets_Step2_Description", resourceCulture);
            }
        }
        
        public static string Assets_Step2_Yes {
            get {
                return ResourceManager.GetString("Assets_Step2_Yes", resourceCulture);
            }
        }
        
        public static string Assets_Step2_No {
            get {
                return ResourceManager.GetString("Assets_Step2_No", resourceCulture);
            }
        }
        
        public static string Assets_Step2_AccountTitle {
            get {
                return ResourceManager.GetString("Assets_Step2_AccountTitle", resourceCulture);
            }
        }
        
        public static string Assets_Step2_Remove {
            get {
                return ResourceManager.GetString("Assets_Step2_Remove", resourceCulture);
            }
        }
        
        public static string Assets_Step2_AccountName {
            get {
                return ResourceManager.GetString("Assets_Step2_AccountName", resourceCulture);
            }
        }
        
        public static string Assets_Step2_AccountNamePlaceholder {
            get {
                return ResourceManager.GetString("Assets_Step2_AccountNamePlaceholder", resourceCulture);
            }
        }
        
        public static string Assets_Step2_AccountTypeQuestion {
            get {
                return ResourceManager.GetString("Assets_Step2_AccountTypeQuestion", resourceCulture);
            }
        }
        
        public static string Assets_Step2_SelectAccountType {
            get {
                return ResourceManager.GetString("Assets_Step2_SelectAccountType", resourceCulture);
            }
        }
        
        public static string Assets_Step2_InputTypeQuestion {
            get {
                return ResourceManager.GetString("Assets_Step2_InputTypeQuestion", resourceCulture);
            }
        }
        
        public static string Assets_Step2_BulkAmountOption {
            get {
                return ResourceManager.GetString("Assets_Step2_BulkAmountOption", resourceCulture);
            }
        }
        
        public static string Assets_Step2_IndividualStocksOption {
            get {
                return ResourceManager.GetString("Assets_Step2_IndividualStocksOption", resourceCulture);
            }
        }
        
        public static string Assets_Step2_TotalAmount {
            get {
                return ResourceManager.GetString("Assets_Step2_TotalAmount", resourceCulture);
            }
        }
        
        public static string Assets_Step2_Stocks {
            get {
                return ResourceManager.GetString("Assets_Step2_Stocks", resourceCulture);
            }
        }
        
        public static string Assets_Step2_TickerPlaceholder {
            get {
                return ResourceManager.GetString("Assets_Step2_TickerPlaceholder", resourceCulture);
            }
        }
        
        public static string Assets_Step2_AmountPlaceholder {
            get {
                return ResourceManager.GetString("Assets_Step2_AmountPlaceholder", resourceCulture);
            }
        }
        
        public static string Assets_Step2_AddStock {
            get {
                return ResourceManager.GetString("Assets_Step2_AddStock", resourceCulture);
            }
        }
        
        public static string Assets_Step2_AddAccount {
            get {
                return ResourceManager.GetString("Assets_Step2_AddAccount", resourceCulture);
            }
        }
        
        public static string Assets_Step2_SaveContinue {
            get {
                return ResourceManager.GetString("Assets_Step2_SaveContinue", resourceCulture);
            }
        }
        
        public static string Assets_Step2_Next {
            get {
                return ResourceManager.GetString("Assets_Step2_Next", resourceCulture);
            }
        }
        
        public static string Assets_Step2_Saving {
            get {
                return ResourceManager.GetString("Assets_Step2_Saving", resourceCulture);
            }
        }
        
        public static string Assets_Step3_Title {
            get {
                return ResourceManager.GetString("Assets_Step3_Title", resourceCulture);
            }
        }
        
        public static string Assets_Step3_Description {
            get {
                return ResourceManager.GetString("Assets_Step3_Description", resourceCulture);
            }
        }
        
        public static string Assets_Step3_Loading {
            get {
                return ResourceManager.GetString("Assets_Step3_Loading", resourceCulture);
            }
        }
        
        public static string Assets_Step3_LoadingMessage {
            get {
                return ResourceManager.GetString("Assets_Step3_LoadingMessage", resourceCulture);
            }
        }
        
        public static string Assets_Step3_Question {
            get {
                return ResourceManager.GetString("Assets_Step3_Question", resourceCulture);
            }
        }
        
        public static string Assets_Step3_Yes {
            get {
                return ResourceManager.GetString("Assets_Step3_Yes", resourceCulture);
            }
        }
        
        public static string Assets_Step3_No {
            get {
                return ResourceManager.GetString("Assets_Step3_No", resourceCulture);
            }
        }
        
        public static string Assets_Step3_NoAssetsAdded {
            get {
                return ResourceManager.GetString("Assets_Step3_NoAssetsAdded", resourceCulture);
            }
        }
        
        public static string Assets_Step3_AssetTitle {
            get {
                return ResourceManager.GetString("Assets_Step3_AssetTitle", resourceCulture);
            }
        }
        
        public static string Assets_Step3_Remove {
            get {
                return ResourceManager.GetString("Assets_Step3_Remove", resourceCulture);
            }
        }
        
        public static string Assets_Step3_AssetName {
            get {
                return ResourceManager.GetString("Assets_Step3_AssetName", resourceCulture);
            }
        }
        
        public static string Assets_Step3_AssetNamePlaceholder {
            get {
                return ResourceManager.GetString("Assets_Step3_AssetNamePlaceholder", resourceCulture);
            }
        }
        
        public static string Assets_Step3_AssetType {
            get {
                return ResourceManager.GetString("Assets_Step3_AssetType", resourceCulture);
            }
        }
        
        public static string Assets_Step3_SelectType {
            get {
                return ResourceManager.GetString("Assets_Step3_SelectType", resourceCulture);
            }
        }
        
        public static string Assets_Step3_CurrentValue {
            get {
                return ResourceManager.GetString("Assets_Step3_CurrentValue", resourceCulture);
            }
        }
        
        public static string Assets_Step3_PurchasePrice {
            get {
                return ResourceManager.GetString("Assets_Step3_PurchasePrice", resourceCulture);
            }
        }
        
        public static string Assets_Step3_PurchasePriceHelp {
            get {
                return ResourceManager.GetString("Assets_Step3_PurchasePriceHelp", resourceCulture);
            }
        }
        
        public static string Assets_Step3_AddAsset {
            get {
                return ResourceManager.GetString("Assets_Step3_AddAsset", resourceCulture);
            }
        }
        
        public static string Assets_Step3_PreviousStep {
            get {
                return ResourceManager.GetString("Assets_Step3_PreviousStep", resourceCulture);
            }
        }
        
        public static string Assets_Step3_SaveContinue {
            get {
                return ResourceManager.GetString("Assets_Step3_SaveContinue", resourceCulture);
            }
        }
        
        public static string Assets_Step3_Required {
            get {
                return ResourceManager.GetString("Assets_Step3_Required", resourceCulture);
            }
        }
        
        public static string Assets_StepComingSoon {
            get {
                return ResourceManager.GetString("Assets_StepComingSoon", resourceCulture);
            }
        }
    }
}
