//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetirementTime.Resources.Introduction {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IntroResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IntroResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RetirementTime.Resources.Introduction.IntroResources", typeof(IntroResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Intro_Back {
            get {
                return ResourceManager.GetString("Intro_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue to.
        /// </summary>
        public static string Intro_ContinueTo {
            get {
                return ResourceManager.GetString("Intro_ContinueTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        public static string Intro_Finish {
            get {
                return ResourceManager.GetString("Intro_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s get started.
        /// </summary>
        public static string Intro_LetsGetStarted {
            get {
                return ResourceManager.GetString("Intro_LetsGetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Intro_Next {
            get {
                return ResourceManager.GetString("Intro_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onboarding.
        /// </summary>
        public static string Intro_Onboarding {
            get {
                return ResourceManager.GetString("Intro_Onboarding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve taken the first step toward a more confident retirement. Nest Egg will guide you through simple questions to assess your current financial situation — from your assets and income to your goals and timeline..
        /// </summary>
        public static string Intro_Step1_Body {
            get {
                return ResourceManager.GetString("Intro_Step1_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ll start by asking you simple introductory questions regarding your current financial situation to help us determine which forms you&apos;ll need to answer later on — making sure you&apos;re not wasting time and receive an accurate retirement projection. You will be able to modify these answers even after completing the introductory section..
        /// </summary>
        public static string Intro_Step1_Body2 {
            get {
                return ResourceManager.GetString("Intro_Step1_Body2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Nest Egg!.
        /// </summary>
        public static string Intro_Step1_Title {
            get {
                return ResourceManager.GetString("Intro_Step1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your citizenship status?.
        /// </summary>
        public static string Intro_Step2_Citizenship {
            get {
                return ResourceManager.GetString("Intro_Step2_Citizenship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canadian.
        /// </summary>
        public static string Intro_Step2_Citizenship_Canadian {
            get {
                return ResourceManager.GetString("Intro_Step2_Citizenship_Canadian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citizen.
        /// </summary>
        public static string Intro_Step2_Citizenship_Citizen {
            get {
                return ResourceManager.GetString("Intro_Step2_Citizenship_Citizen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Intro_Step2_Citizenship_Other {
            get {
                return ResourceManager.GetString("Intro_Step2_Citizenship_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanent Resident.
        /// </summary>
        public static string Intro_Step2_Citizenship_PermanentResident {
            get {
                return ResourceManager.GetString("Intro_Step2_Citizenship_PermanentResident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your citizenship status.
        /// </summary>
        public static string Intro_Step2_Citizenship_Select {
            get {
                return ResourceManager.GetString("Intro_Step2_Citizenship_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary Resident.
        /// </summary>
        public static string Intro_Step2_Citizenship_TemporaryResident {
            get {
                return ResourceManager.GetString("Intro_Step2_Citizenship_TemporaryResident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to American.
        /// </summary>
        public static string Intro_Step2_Citizenship_US {
            get {
                return ResourceManager.GetString("Intro_Step2_Citizenship_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you currently have children?.
        /// </summary>
        public static string Intro_Step2_CurrentChildren {
            get {
                return ResourceManager.GetString("Intro_Step2_CurrentChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helps estimate current and future financial obligations..
        /// </summary>
        public static string Intro_Step2_CurrentChildren_Hint {
            get {
                return ResourceManager.GetString("Intro_Step2_CurrentChildren_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your date of birth?.
        /// </summary>
        public static string Intro_Step2_DateOfBirth {
            get {
                return ResourceManager.GetString("Intro_Step2_DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your email address?.
        /// </summary>
        public static string Intro_Step2_Email {
            get {
                return ResourceManager.GetString("Intro_Step2_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string Intro_Step2_FirstName {
            get {
                return ResourceManager.GetString("Intro_Step2_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you planning to have children in the future?.
        /// </summary>
        public static string Intro_Step2_FutureChildren {
            get {
                return ResourceManager.GetString("Intro_Step2_FutureChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May affect your savings timeline and retirement target..
        /// </summary>
        public static string Intro_Step2_FutureChildren_Hint {
            get {
                return ResourceManager.GetString("Intro_Step2_FutureChildren_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to include your partner in the retirement plan?.
        /// </summary>
        public static string Intro_Step2_IncludePartner {
            get {
                return ResourceManager.GetString("Intro_Step2_IncludePartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ll factor their income, savings, and goals into your shared plan..
        /// </summary>
        public static string Intro_Step2_IncludePartner_Hint {
            get {
                return ResourceManager.GetString("Intro_Step2_IncludePartner_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string Intro_Step2_LastName {
            get {
                return ResourceManager.GetString("Intro_Step2_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your marital status?.
        /// </summary>
        public static string Intro_Step2_MaritalStatus {
            get {
                return ResourceManager.GetString("Intro_Step2_MaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common-law.
        /// </summary>
        public static string Intro_Step2_MaritalStatus_CommonLaw {
            get {
                return ResourceManager.GetString("Intro_Step2_MaritalStatus_CommonLaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divorced.
        /// </summary>
        public static string Intro_Step2_MaritalStatus_Divorced {
            get {
                return ResourceManager.GetString("Intro_Step2_MaritalStatus_Divorced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Married.
        /// </summary>
        public static string Intro_Step2_MaritalStatus_Married {
            get {
                return ResourceManager.GetString("Intro_Step2_MaritalStatus_Married", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your marital status.
        /// </summary>
        public static string Intro_Step2_MaritalStatus_Select {
            get {
                return ResourceManager.GetString("Intro_Step2_MaritalStatus_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        public static string Intro_Step2_MaritalStatus_Single {
            get {
                return ResourceManager.GetString("Intro_Step2_MaritalStatus_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widowed.
        /// </summary>
        public static string Intro_Step2_MaritalStatus_Widowed {
            get {
                return ResourceManager.GetString("Intro_Step2_MaritalStatus_Widowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your name?.
        /// </summary>
        public static string Intro_Step2_Name {
            get {
                return ResourceManager.GetString("Intro_Step2_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Intro_Step2_No {
            get {
                return ResourceManager.GetString("Intro_Step2_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1 of 5 — Personal Information.
        /// </summary>
        public static string Intro_Step2_Preface {
            get {
                return ResourceManager.GetString("Intro_Step2_Preface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your personal profile helps us tailor tax strategies, contribution room estimates, and government benefit projections (CPP, OAS, GIS) specifically to your situation..
        /// </summary>
        public static string Intro_Step2_Sidebar_Body {
            get {
                return ResourceManager.GetString("Intro_Step2_Sidebar_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your data is encrypted and never shared..
        /// </summary>
        public static string Intro_Step2_Sidebar_Security {
            get {
                return ResourceManager.GetString("Intro_Step2_Sidebar_Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your citizenship and marital status directly impact your RRSP/TFSA contribution limits and eligibility for spousal splitting strategies in retirement..
        /// </summary>
        public static string Intro_Step2_Sidebar_TaxBody {
            get {
                return ResourceManager.GetString("Intro_Step2_Sidebar_TaxBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax residency matters.
        /// </summary>
        public static string Intro_Step2_Sidebar_TaxTitle {
            get {
                return ResourceManager.GetString("Intro_Step2_Sidebar_TaxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why do we ask?.
        /// </summary>
        public static string Intro_Step2_Sidebar_Title {
            get {
                return ResourceManager.GetString("Intro_Step2_Sidebar_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s start by gathering a bit of information about yourself..
        /// </summary>
        public static string Intro_Step2_Subtitle {
            get {
                return ResourceManager.GetString("Intro_Step2_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        public static string Intro_Step2_Title {
            get {
                return ResourceManager.GetString("Intro_Step2_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Intro_Step2_Yes {
            get {
                return ResourceManager.GetString("Intro_Step2_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business (sole proprietorship or partnership).
        /// </summary>
        public static string Intro_Step3_HasBusiness {
            get {
                return ResourceManager.GetString("Intro_Step3_HasBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car or other personal vehicles.
        /// </summary>
        public static string Intro_Step3_HasCar {
            get {
                return ResourceManager.GetString("Intro_Step3_HasCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Home Savings Account (FHSA).
        /// </summary>
        public static string Intro_Step3_HasFHSA {
            get {
                return ResourceManager.GetString("Intro_Step3_HasFHSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporation or professional incorporation.
        /// </summary>
        public static string Intro_Step3_HasIncorporation {
            get {
                return ResourceManager.GetString("Intro_Step3_HasIncorporation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investment or rental property.
        /// </summary>
        public static string Intro_Step3_HasInvestmentProperty {
            get {
                return ResourceManager.GetString("Intro_Step3_HasInvestmentProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-registered investment account (stocks, ETFs, mutual funds, etc.).
        /// </summary>
        public static string Intro_Step3_HasNonRegistered {
            get {
                return ResourceManager.GetString("Intro_Step3_HasNonRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other hard assets (art, collectibles, equipment, etc.).
        /// </summary>
        public static string Intro_Step3_HasOtherHardAssets {
            get {
                return ResourceManager.GetString("Intro_Step3_HasOtherHardAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workplace pension plan (DBPP or DCPP).
        /// </summary>
        public static string Intro_Step3_HasPension {
            get {
                return ResourceManager.GetString("Intro_Step3_HasPension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical precious metals (gold, silver, etc.).
        /// </summary>
        public static string Intro_Step3_HasPreciousMetals {
            get {
                return ResourceManager.GetString("Intro_Step3_HasPreciousMetals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal residence (home you live in).
        /// </summary>
        public static string Intro_Step3_HasPrincipalResidence {
            get {
                return ResourceManager.GetString("Intro_Step3_HasPrincipalResidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Disability Savings Plan (RDSP).
        /// </summary>
        public static string Intro_Step3_HasRDSP {
            get {
                return ResourceManager.GetString("Intro_Step3_HasRDSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Education Savings Plan (RESP).
        /// </summary>
        public static string Intro_Step3_HasRESP {
            get {
                return ResourceManager.GetString("Intro_Step3_HasRESP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Retirement Income Fund (RRIF).
        /// </summary>
        public static string Intro_Step3_HasRRIF {
            get {
                return ResourceManager.GetString("Intro_Step3_HasRRIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Retirement Savings Plan (RRSP).
        /// </summary>
        public static string Intro_Step3_HasRRSP {
            get {
                return ResourceManager.GetString("Intro_Step3_HasRRSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have any cash account(s) (e.g. chequing, savings, high-yield savings)?.
        /// </summary>
        public static string Intro_Step3_HasSavingsAccount {
            get {
                return ResourceManager.GetString("Intro_Step3_HasSavingsAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax-Free Savings Account (TFSA).
        /// </summary>
        public static string Intro_Step3_HasTFSA {
            get {
                return ResourceManager.GetString("Intro_Step3_HasTFSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which of the following investment or registered account(s) do you have?.
        /// </summary>
        public static string Intro_Step3_InvestmentAccounts {
            get {
                return ResourceManager.GetString("Intro_Step3_InvestmentAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Intro_Step3_No {
            get {
                return ResourceManager.GetString("Intro_Step3_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which of the following physical asset(s) do you own?.
        /// </summary>
        public static string Intro_Step3_PhysicalAssets {
            get {
                return ResourceManager.GetString("Intro_Step3_PhysicalAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Accounts.
        /// </summary>
        public static string Intro_Step3_Section_Financial {
            get {
                return ResourceManager.GetString("Intro_Step3_Section_Financial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Assets.
        /// </summary>
        public static string Intro_Step3_Section_Physical {
            get {
                return ResourceManager.GetString("Intro_Step3_Section_Physical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Accounts.
        /// </summary>
        public static string Intro_Step3_Section_Savings {
            get {
                return ResourceManager.GetString("Intro_Step3_Section_Savings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help us understand the types of investments and assets you currently have..
        /// </summary>
        public static string Intro_Step3_Subtitle {
            get {
                return ResourceManager.GetString("Intro_Step3_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Assets.
        /// </summary>
        public static string Intro_Step3_Title {
            get {
                return ResourceManager.GetString("Intro_Step3_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Intro_Step3_Yes {
            get {
                return ResourceManager.GetString("Intro_Step3_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business loan or business line of credit.
        /// </summary>
        public static string Intro_Step4_BusinessLoans {
            get {
                return ResourceManager.GetString("Intro_Step4_BusinessLoans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car loan or vehicle financing.
        /// </summary>
        public static string Intro_Step4_CarPayments {
            get {
                return ResourceManager.GetString("Intro_Step4_CarPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit card debt.
        /// </summary>
        public static string Intro_Step4_CreditCardDebt {
            get {
                return ResourceManager.GetString("Intro_Step4_CreditCardDebt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which of the following debt(s) do you currently have?.
        /// </summary>
        public static string Intro_Step4_DebtQuestion {
            get {
                return ResourceManager.GetString("Intro_Step4_DebtQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informal debt (family or personal loans).
        /// </summary>
        public static string Intro_Step4_InformalDebt {
            get {
                return ResourceManager.GetString("Intro_Step4_InformalDebt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mortgage on investment or rental property.
        /// </summary>
        public static string Intro_Step4_InvestmentPropertyMortgage {
            get {
                return ResourceManager.GetString("Intro_Step4_InvestmentPropertyMortgage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical or dental debt.
        /// </summary>
        public static string Intro_Step4_MedicalDebt {
            get {
                return ResourceManager.GetString("Intro_Step4_MedicalDebt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal loan or line of credit.
        /// </summary>
        public static string Intro_Step4_PersonalLoans {
            get {
                return ResourceManager.GetString("Intro_Step4_PersonalLoans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mortgage on principal residence.
        /// </summary>
        public static string Intro_Step4_PrimaryMortgage {
            get {
                return ResourceManager.GetString("Intro_Step4_PrimaryMortgage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student loans.
        /// </summary>
        public static string Intro_Step4_StudentLoans {
            get {
                return ResourceManager.GetString("Intro_Step4_StudentLoans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Understanding your current debt helps us build a more accurate retirement plan..
        /// </summary>
        public static string Intro_Step4_Subtitle {
            get {
                return ResourceManager.GetString("Intro_Step4_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax debt (e.g. owing to the CRA).
        /// </summary>
        public static string Intro_Step4_TaxDebt {
            get {
                return ResourceManager.GetString("Intro_Step4_TaxDebt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Debt.
        /// </summary>
        public static string Intro_Step4_Title {
            get {
                return ResourceManager.GetString("Intro_Step4_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many years have you contributed to the Canada Pension Plan (CPP)?.
        /// </summary>
        public static string Intro_Step5_CppYears {
            get {
                return ResourceManager.GetString("Intro_Step5_CppYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dividends from stocks or business ownership.
        /// </summary>
        public static string Intro_Step5_Dividends {
            get {
                return ResourceManager.GetString("Intro_Step5_Dividends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you currently employed by an employer?.
        /// </summary>
        public static string Intro_Step5_IsEmployed {
            get {
                return ResourceManager.GetString("Intro_Step5_IsEmployed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you self-employed or a freelancer?.
        /// </summary>
        public static string Intro_Step5_IsSelfEmployed {
            get {
                return ResourceManager.GetString("Intro_Step5_IsSelfEmployed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Intro_Step5_No {
            get {
                return ResourceManager.GetString("Intro_Step5_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you receiving any of the following regular income sources?.
        /// </summary>
        public static string Intro_Step5_OtherIncome {
            get {
                return ResourceManager.GetString("Intro_Step5_OtherIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other regular income.
        /// </summary>
        public static string Intro_Step5_OtherIncomeItem {
            get {
                return ResourceManager.GetString("Intro_Step5_OtherIncomeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental income from properties.
        /// </summary>
        public static string Intro_Step5_RentalIncome {
            get {
                return ResourceManager.GetString("Intro_Step5_RentalIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At what age do you plan to retire?.
        /// </summary>
        public static string Intro_Step5_RetirementAge {
            get {
                return ResourceManager.GetString("Intro_Step5_RetirementAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Royalties (books, music, patents, etc.).
        /// </summary>
        public static string Intro_Step5_Royalties {
            get {
                return ResourceManager.GetString("Intro_Step5_Royalties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employment.
        /// </summary>
        public static string Intro_Step5_Section_Employment {
            get {
                return ResourceManager.GetString("Intro_Step5_Section_Employment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Income.
        /// </summary>
        public static string Intro_Step5_Section_Income {
            get {
                return ResourceManager.GetString("Intro_Step5_Section_Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell us about your current employment situation and any additional sources of income..
        /// </summary>
        public static string Intro_Step5_Subtitle {
            get {
                return ResourceManager.GetString("Intro_Step5_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employment &amp; Income.
        /// </summary>
        public static string Intro_Step5_Title {
            get {
                return ResourceManager.GetString("Intro_Step5_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Intro_Step5_Yes {
            get {
                return ResourceManager.GetString("Intro_Step5_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step {0} of {1}.
        /// </summary>
        public static string Intro_StepOf {
            get {
                return ResourceManager.GetString("Intro_StepOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s get to know you a little better so we can tailor your retirement plan..
        /// </summary>
        public static string Intro_Subtitle {
            get {
                return ResourceManager.GetString("Intro_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Nest Egg.
        /// </summary>
        public static string Intro_Title {
            get {
                return ResourceManager.GetString("Intro_Title", resourceCulture);
            }
        }
    }
}
