//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetirementTime.Resources.Introduction {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IntroResources_fr_CA {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IntroResources_fr_CA() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("RetirementTime.Resources.Introduction.IntroResources_fr_CA", typeof(IntroResources_fr_CA).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Intro_Title {
            get {
                return ResourceManager.GetString("Intro_Title", resourceCulture);
            }
        }
        
        public static string Intro_Onboarding {
            get {
                return ResourceManager.GetString("Intro_Onboarding", resourceCulture);
            }
        }
        
        public static string Intro_Subtitle {
            get {
                return ResourceManager.GetString("Intro_Subtitle", resourceCulture);
            }
        }
        
        public static string Intro_Next {
            get {
                return ResourceManager.GetString("Intro_Next", resourceCulture);
            }
        }
        
        public static string Intro_Back {
            get {
                return ResourceManager.GetString("Intro_Back", resourceCulture);
            }
        }
        
        public static string Intro_ContinueTo {
            get {
                return ResourceManager.GetString("Intro_ContinueTo", resourceCulture);
            }
        }
        
        public static string Intro_Finish {
            get {
                return ResourceManager.GetString("Intro_Finish", resourceCulture);
            }
        }
        
        public static string Intro_StepOf {
            get {
                return ResourceManager.GetString("Intro_StepOf", resourceCulture);
            }
        }
        
        public static string Intro_LetsGetStarted {
            get {
                return ResourceManager.GetString("Intro_LetsGetStarted", resourceCulture);
            }
        }
        
        public static string Intro_Step1_Title {
            get {
                return ResourceManager.GetString("Intro_Step1_Title", resourceCulture);
            }
        }
        
        public static string Intro_Step1_Body {
            get {
                return ResourceManager.GetString("Intro_Step1_Body", resourceCulture);
            }
        }
        
        public static string Intro_Step1_Body2 {
            get {
                return ResourceManager.GetString("Intro_Step1_Body2", resourceCulture);
            }
        }
        
        public static string Intro_Step2_Title {
            get {
                return ResourceManager.GetString("Intro_Step2_Title", resourceCulture);
            }
        }
        
        public static string Intro_Step2_Subtitle {
            get {
                return ResourceManager.GetString("Intro_Step2_Subtitle", resourceCulture);
            }
        }
        
        public static string Intro_Step2_Email {
            get {
                return ResourceManager.GetString("Intro_Step2_Email", resourceCulture);
            }
        }
        
        public static string Intro_Step2_Name {
            get {
                return ResourceManager.GetString("Intro_Step2_Name", resourceCulture);
            }
        }
        
        public static string Intro_Step2_FirstName {
            get {
                return ResourceManager.GetString("Intro_Step2_FirstName", resourceCulture);
            }
        }
        
        public static string Intro_Step2_LastName {
            get {
                return ResourceManager.GetString("Intro_Step2_LastName", resourceCulture);
            }
        }
        
        public static string Intro_Step2_DateOfBirth {
            get {
                return ResourceManager.GetString("Intro_Step2_DateOfBirth", resourceCulture);
            }
        }
        
        public static string Intro_Step2_Citizenship {
            get {
                return ResourceManager.GetString("Intro_Step2_Citizenship", resourceCulture);
            }
        }
        
        public static string Intro_Step2_Citizenship_Citizen {
            get {
                return ResourceManager.GetString("Intro_Step2_Citizenship_Citizen", resourceCulture);
            }
        }
        
        public static string Intro_Step2_Citizenship_Canadian {
            get {
                return ResourceManager.GetString("Intro_Step2_Citizenship_Canadian", resourceCulture);
            }
        }
        
        public static string Intro_Step2_Citizenship_US {
            get {
                return ResourceManager.GetString("Intro_Step2_Citizenship_US", resourceCulture);
            }
        }
        
        public static string Intro_Step2_Citizenship_PermanentResident {
            get {
                return ResourceManager.GetString("Intro_Step2_Citizenship_PermanentResident", resourceCulture);
            }
        }
        
        public static string Intro_Step2_Citizenship_TemporaryResident {
            get {
                return ResourceManager.GetString("Intro_Step2_Citizenship_TemporaryResident", resourceCulture);
            }
        }
        
        public static string Intro_Step2_Citizenship_Other {
            get {
                return ResourceManager.GetString("Intro_Step2_Citizenship_Other", resourceCulture);
            }
        }
        
        public static string Intro_Step2_Citizenship_Select {
            get {
                return ResourceManager.GetString("Intro_Step2_Citizenship_Select", resourceCulture);
            }
        }
        
        public static string Intro_Step2_MaritalStatus {
            get {
                return ResourceManager.GetString("Intro_Step2_MaritalStatus", resourceCulture);
            }
        }
        
        public static string Intro_Step2_MaritalStatus_Single {
            get {
                return ResourceManager.GetString("Intro_Step2_MaritalStatus_Single", resourceCulture);
            }
        }
        
        public static string Intro_Step2_MaritalStatus_Married {
            get {
                return ResourceManager.GetString("Intro_Step2_MaritalStatus_Married", resourceCulture);
            }
        }
        
        public static string Intro_Step2_MaritalStatus_CommonLaw {
            get {
                return ResourceManager.GetString("Intro_Step2_MaritalStatus_CommonLaw", resourceCulture);
            }
        }
        
        public static string Intro_Step2_MaritalStatus_Divorced {
            get {
                return ResourceManager.GetString("Intro_Step2_MaritalStatus_Divorced", resourceCulture);
            }
        }
        
        public static string Intro_Step2_MaritalStatus_Widowed {
            get {
                return ResourceManager.GetString("Intro_Step2_MaritalStatus_Widowed", resourceCulture);
            }
        }
        
        public static string Intro_Step2_MaritalStatus_Select {
            get {
                return ResourceManager.GetString("Intro_Step2_MaritalStatus_Select", resourceCulture);
            }
        }
        
        public static string Intro_Step2_CurrentChildren {
            get {
                return ResourceManager.GetString("Intro_Step2_CurrentChildren", resourceCulture);
            }
        }
        
        public static string Intro_Step2_FutureChildren {
            get {
                return ResourceManager.GetString("Intro_Step2_FutureChildren", resourceCulture);
            }
        }
        
        public static string Intro_Step2_IncludePartner {
            get {
                return ResourceManager.GetString("Intro_Step2_IncludePartner", resourceCulture);
            }
        }
        
        public static string Intro_Step2_Yes {
            get {
                return ResourceManager.GetString("Intro_Step2_Yes", resourceCulture);
            }
        }
        
        public static string Intro_Step2_No {
            get {
                return ResourceManager.GetString("Intro_Step2_No", resourceCulture);
            }
        }
        
        public static string Intro_Step2_Preface {
            get {
                return ResourceManager.GetString("Intro_Step2_Preface", resourceCulture);
            }
        }
        
        public static string Intro_Step2_IncludePartner_Hint {
            get {
                return ResourceManager.GetString("Intro_Step2_IncludePartner_Hint", resourceCulture);
            }
        }
        
        public static string Intro_Step2_CurrentChildren_Hint {
            get {
                return ResourceManager.GetString("Intro_Step2_CurrentChildren_Hint", resourceCulture);
            }
        }
        
        public static string Intro_Step2_FutureChildren_Hint {
            get {
                return ResourceManager.GetString("Intro_Step2_FutureChildren_Hint", resourceCulture);
            }
        }
        
        public static string Intro_Step2_Sidebar_Title {
            get {
                return ResourceManager.GetString("Intro_Step2_Sidebar_Title", resourceCulture);
            }
        }
        
        public static string Intro_Step2_Sidebar_Body {
            get {
                return ResourceManager.GetString("Intro_Step2_Sidebar_Body", resourceCulture);
            }
        }
        
        public static string Intro_Step2_Sidebar_Security {
            get {
                return ResourceManager.GetString("Intro_Step2_Sidebar_Security", resourceCulture);
            }
        }
        
        public static string Intro_Step2_Sidebar_TaxTitle {
            get {
                return ResourceManager.GetString("Intro_Step2_Sidebar_TaxTitle", resourceCulture);
            }
        }
        
        public static string Intro_Step2_Sidebar_TaxBody {
            get {
                return ResourceManager.GetString("Intro_Step2_Sidebar_TaxBody", resourceCulture);
            }
        }
        
        public static string Intro_Step3_Title {
            get {
                return ResourceManager.GetString("Intro_Step3_Title", resourceCulture);
            }
        }
        
        public static string Intro_Step3_Subtitle {
            get {
                return ResourceManager.GetString("Intro_Step3_Subtitle", resourceCulture);
            }
        }
        
        public static string Intro_Step3_Yes {
            get {
                return ResourceManager.GetString("Intro_Step3_Yes", resourceCulture);
            }
        }
        
        public static string Intro_Step3_No {
            get {
                return ResourceManager.GetString("Intro_Step3_No", resourceCulture);
            }
        }
        
        public static string Intro_Step3_Section_Savings {
            get {
                return ResourceManager.GetString("Intro_Step3_Section_Savings", resourceCulture);
            }
        }
        
        public static string Intro_Step3_Section_Financial {
            get {
                return ResourceManager.GetString("Intro_Step3_Section_Financial", resourceCulture);
            }
        }
        
        public static string Intro_Step3_HasSavingsAccount {
            get {
                return ResourceManager.GetString("Intro_Step3_HasSavingsAccount", resourceCulture);
            }
        }
        
        public static string Intro_Step3_InvestmentAccounts {
            get {
                return ResourceManager.GetString("Intro_Step3_InvestmentAccounts", resourceCulture);
            }
        }
        
        public static string Intro_Step3_HasTFSA {
            get {
                return ResourceManager.GetString("Intro_Step3_HasTFSA", resourceCulture);
            }
        }
        
        public static string Intro_Step3_HasRRSP {
            get {
                return ResourceManager.GetString("Intro_Step3_HasRRSP", resourceCulture);
            }
        }
        
        public static string Intro_Step3_HasRRIF {
            get {
                return ResourceManager.GetString("Intro_Step3_HasRRIF", resourceCulture);
            }
        }
        
        public static string Intro_Step3_HasFHSA {
            get {
                return ResourceManager.GetString("Intro_Step3_HasFHSA", resourceCulture);
            }
        }
        
        public static string Intro_Step3_HasRESP {
            get {
                return ResourceManager.GetString("Intro_Step3_HasRESP", resourceCulture);
            }
        }
        
        public static string Intro_Step3_HasRDSP {
            get {
                return ResourceManager.GetString("Intro_Step3_HasRDSP", resourceCulture);
            }
        }
        
        public static string Intro_Step3_HasNonRegistered {
            get {
                return ResourceManager.GetString("Intro_Step3_HasNonRegistered", resourceCulture);
            }
        }
        
        public static string Intro_Step3_HasPension {
            get {
                return ResourceManager.GetString("Intro_Step3_HasPension", resourceCulture);
            }
        }
        
        public static string Intro_Step3_Section_Physical {
            get {
                return ResourceManager.GetString("Intro_Step3_Section_Physical", resourceCulture);
            }
        }
        
        public static string Intro_Step3_PhysicalAssets {
            get {
                return ResourceManager.GetString("Intro_Step3_PhysicalAssets", resourceCulture);
            }
        }
        
        public static string Intro_Step3_HasPrincipalResidence {
            get {
                return ResourceManager.GetString("Intro_Step3_HasPrincipalResidence", resourceCulture);
            }
        }
        
        public static string Intro_Step3_HasCar {
            get {
                return ResourceManager.GetString("Intro_Step3_HasCar", resourceCulture);
            }
        }
        
        public static string Intro_Step3_HasInvestmentProperty {
            get {
                return ResourceManager.GetString("Intro_Step3_HasInvestmentProperty", resourceCulture);
            }
        }
        
        public static string Intro_Step3_HasBusiness {
            get {
                return ResourceManager.GetString("Intro_Step3_HasBusiness", resourceCulture);
            }
        }
        
        public static string Intro_Step3_HasIncorporation {
            get {
                return ResourceManager.GetString("Intro_Step3_HasIncorporation", resourceCulture);
            }
        }
        
        public static string Intro_Step3_HasPreciousMetals {
            get {
                return ResourceManager.GetString("Intro_Step3_HasPreciousMetals", resourceCulture);
            }
        }
        
        public static string Intro_Step3_HasOtherHardAssets {
            get {
                return ResourceManager.GetString("Intro_Step3_HasOtherHardAssets", resourceCulture);
            }
        }
        
        public static string Intro_Step4_Title {
            get {
                return ResourceManager.GetString("Intro_Step4_Title", resourceCulture);
            }
        }
        
        public static string Intro_Step4_Subtitle {
            get {
                return ResourceManager.GetString("Intro_Step4_Subtitle", resourceCulture);
            }
        }
        
        public static string Intro_Step4_DebtQuestion {
            get {
                return ResourceManager.GetString("Intro_Step4_DebtQuestion", resourceCulture);
            }
        }
        
        public static string Intro_Step4_PrimaryMortgage {
            get {
                return ResourceManager.GetString("Intro_Step4_PrimaryMortgage", resourceCulture);
            }
        }
        
        public static string Intro_Step4_InvestmentPropertyMortgage {
            get {
                return ResourceManager.GetString("Intro_Step4_InvestmentPropertyMortgage", resourceCulture);
            }
        }
        
        public static string Intro_Step4_CarPayments {
            get {
                return ResourceManager.GetString("Intro_Step4_CarPayments", resourceCulture);
            }
        }
        
        public static string Intro_Step4_StudentLoans {
            get {
                return ResourceManager.GetString("Intro_Step4_StudentLoans", resourceCulture);
            }
        }
        
        public static string Intro_Step4_CreditCardDebt {
            get {
                return ResourceManager.GetString("Intro_Step4_CreditCardDebt", resourceCulture);
            }
        }
        
        public static string Intro_Step4_PersonalLoans {
            get {
                return ResourceManager.GetString("Intro_Step4_PersonalLoans", resourceCulture);
            }
        }
        
        public static string Intro_Step4_BusinessLoans {
            get {
                return ResourceManager.GetString("Intro_Step4_BusinessLoans", resourceCulture);
            }
        }
        
        public static string Intro_Step4_TaxDebt {
            get {
                return ResourceManager.GetString("Intro_Step4_TaxDebt", resourceCulture);
            }
        }
        
        public static string Intro_Step4_MedicalDebt {
            get {
                return ResourceManager.GetString("Intro_Step4_MedicalDebt", resourceCulture);
            }
        }
        
        public static string Intro_Step4_InformalDebt {
            get {
                return ResourceManager.GetString("Intro_Step4_InformalDebt", resourceCulture);
            }
        }
        
        public static string Intro_Step5_Title {
            get {
                return ResourceManager.GetString("Intro_Step5_Title", resourceCulture);
            }
        }
        
        public static string Intro_Step5_Subtitle {
            get {
                return ResourceManager.GetString("Intro_Step5_Subtitle", resourceCulture);
            }
        }
        
        public static string Intro_Step5_Yes {
            get {
                return ResourceManager.GetString("Intro_Step5_Yes", resourceCulture);
            }
        }
        
        public static string Intro_Step5_No {
            get {
                return ResourceManager.GetString("Intro_Step5_No", resourceCulture);
            }
        }
        
        public static string Intro_Step5_Section_Employment {
            get {
                return ResourceManager.GetString("Intro_Step5_Section_Employment", resourceCulture);
            }
        }
        
        public static string Intro_Step5_IsEmployed {
            get {
                return ResourceManager.GetString("Intro_Step5_IsEmployed", resourceCulture);
            }
        }
        
        public static string Intro_Step5_IsSelfEmployed {
            get {
                return ResourceManager.GetString("Intro_Step5_IsSelfEmployed", resourceCulture);
            }
        }
        
        public static string Intro_Step5_RetirementAge {
            get {
                return ResourceManager.GetString("Intro_Step5_RetirementAge", resourceCulture);
            }
        }
        
        public static string Intro_Step5_CppYears {
            get {
                return ResourceManager.GetString("Intro_Step5_CppYears", resourceCulture);
            }
        }
        
        public static string Intro_Step5_Section_Income {
            get {
                return ResourceManager.GetString("Intro_Step5_Section_Income", resourceCulture);
            }
        }
        
        public static string Intro_Step5_OtherIncome {
            get {
                return ResourceManager.GetString("Intro_Step5_OtherIncome", resourceCulture);
            }
        }
        
        public static string Intro_Step5_Royalties {
            get {
                return ResourceManager.GetString("Intro_Step5_Royalties", resourceCulture);
            }
        }
        
        public static string Intro_Step5_Dividends {
            get {
                return ResourceManager.GetString("Intro_Step5_Dividends", resourceCulture);
            }
        }
        
        public static string Intro_Step5_RentalIncome {
            get {
                return ResourceManager.GetString("Intro_Step5_RentalIncome", resourceCulture);
            }
        }
        
        public static string Intro_Step5_OtherIncomeItem {
            get {
                return ResourceManager.GetString("Intro_Step5_OtherIncomeItem", resourceCulture);
            }
        }
    }
}
