// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RetirementTime.Infrastructure;

#nullable disable

namespace RetirementTime.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260322194330_AddOnboardingStep1PersonalInfo")]
    partial class AddOnboardingStep1PersonalInfo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RetirementTime.Domain.Entities.Common.Frequency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FrequencyPerYear")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("common_frequencies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FrequencyPerYear = 52,
                            Name = "Weekly"
                        },
                        new
                        {
                            Id = 2,
                            FrequencyPerYear = 26,
                            Name = "Bi-Weekly"
                        },
                        new
                        {
                            Id = 3,
                            FrequencyPerYear = 12,
                            Name = "Monthly"
                        },
                        new
                        {
                            Id = 4,
                            FrequencyPerYear = 6,
                            Name = "Bi-Monthly"
                        },
                        new
                        {
                            Id = 5,
                            FrequencyPerYear = 4,
                            Name = "Quarterly"
                        },
                        new
                        {
                            Id = 6,
                            FrequencyPerYear = 2,
                            Name = "Semi-Annually"
                        },
                        new
                        {
                            Id = 7,
                            FrequencyPerYear = 1,
                            Name = "Annually"
                        });
                });

            modelBuilder.Entity("RetirementTime.Domain.Entities.Language", b =>
                {
                    b.Property<string>("LanguageCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("LanguageCode");

                    b.ToTable("language", (string)null);

                    b.HasData(
                        new
                        {
                            LanguageCode = "en",
                            LanguageName = "English"
                        },
                        new
                        {
                            LanguageCode = "fr",
                            LanguageName = "French"
                        });
                });

            modelBuilder.Entity("RetirementTime.Domain.Entities.Location.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("country", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryCode = "CA",
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 2,
                            CountryCode = "US",
                            Name = "United States"
                        });
                });

            modelBuilder.Entity("RetirementTime.Domain.Entities.Location.Subdivision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("CountryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("subdivision", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "AB",
                            CountryId = 1,
                            Name = "Alberta"
                        },
                        new
                        {
                            Id = 2,
                            Code = "BC",
                            CountryId = 1,
                            Name = "British Columbia"
                        },
                        new
                        {
                            Id = 3,
                            Code = "MB",
                            CountryId = 1,
                            Name = "Manitoba"
                        },
                        new
                        {
                            Id = 4,
                            Code = "NB",
                            CountryId = 1,
                            Name = "New Brunswick"
                        },
                        new
                        {
                            Id = 5,
                            Code = "NL",
                            CountryId = 1,
                            Name = "Newfoundland and Labrador"
                        },
                        new
                        {
                            Id = 6,
                            Code = "NS",
                            CountryId = 1,
                            Name = "Nova Scotia"
                        },
                        new
                        {
                            Id = 7,
                            Code = "ON",
                            CountryId = 1,
                            Name = "Ontario"
                        },
                        new
                        {
                            Id = 8,
                            Code = "PE",
                            CountryId = 1,
                            Name = "Prince Edward Island"
                        },
                        new
                        {
                            Id = 9,
                            Code = "QC",
                            CountryId = 1,
                            Name = "Quebec"
                        },
                        new
                        {
                            Id = 10,
                            Code = "SK",
                            CountryId = 1,
                            Name = "Saskatchewan"
                        },
                        new
                        {
                            Id = 11,
                            Code = "NT",
                            CountryId = 1,
                            Name = "Northwest Territories"
                        },
                        new
                        {
                            Id = 12,
                            Code = "NU",
                            CountryId = 1,
                            Name = "Nunavut"
                        },
                        new
                        {
                            Id = 13,
                            Code = "YT",
                            CountryId = 1,
                            Name = "Yukon"
                        });
                });

            modelBuilder.Entity("RetirementTime.Domain.Entities.Onboarding.OnboardingPersonalInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CitizenshipStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("HasCurrentChildren")
                        .HasColumnType("boolean");

                    b.Property<bool>("IncludePartner")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MaritalStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("PlansFutureChildren")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("onboarding_step1_personal_info", (string)null);
                });

            modelBuilder.Entity("RetirementTime.Domain.Entities.RealEstate.BuyOrRent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ComparisonTimeframeInYears")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<int>("MortgageId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double>("PercentDifferenceReinvested")
                        .HasColumnType("double precision");

                    b.Property<double>("PercentDifferenceReinvestedGrowthRate")
                        .HasColumnType("double precision");

                    b.Property<int>("RentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.HasKey("Id");

                    b.HasIndex("MortgageId");

                    b.HasIndex("RentId");

                    b.ToTable("buy_or_rent", (string)null);
                });

            modelBuilder.Entity("RetirementTime.Domain.Entities.RealEstate.Mortgage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AdditionalCosts")
                        .HasColumnType("double precision");

                    b.Property<double>("AdditionalMonthlyCosts")
                        .HasColumnType("double precision");

                    b.Property<double>("ClosingCosts")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<double>("DownPayment")
                        .HasColumnType("double precision");

                    b.Property<double>("InterestRate")
                        .HasColumnType("double precision");

                    b.Property<double>("MonthlyMortgageInsuranceCosts")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("RealEstateId")
                        .HasColumnType("integer");

                    b.Property<int>("TermInYears")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.HasKey("Id");

                    b.HasIndex("RealEstateId");

                    b.ToTable("mortgage", (string)null);
                });

            modelBuilder.Entity("RetirementTime.Domain.Entities.RealEstate.RealEstate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<double>("MonthlyElectricityCosts")
                        .HasColumnType("double precision");

                    b.Property<double>("MonthlyInsuranceCosts")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double>("PercentYearlyExpenses")
                        .HasColumnType("double precision");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<double>("YearlyAppreciation")
                        .HasColumnType("double precision");

                    b.Property<double>("YearlyHoaCosts")
                        .HasColumnType("double precision");

                    b.Property<double>("YearlyTaxesPercent")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("real_estate", (string)null);
                });

            modelBuilder.Entity("RetirementTime.Domain.Entities.RealEstate.Rent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<double>("MonthlyElectricityCosts")
                        .HasColumnType("double precision");

                    b.Property<double>("MonthlyInsuranceCosts")
                        .HasColumnType("double precision");

                    b.Property<double>("MonthlyRent")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<double>("YearlyRentIncrease")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("rent", (string)null);
                });

            modelBuilder.Entity("RetirementTime.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "User"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("RetirementTime.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasCompletedIntro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("en");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<long?>("SpouseId")
                        .HasColumnType("bigint");

                    b.Property<int?>("SubdivisionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("LanguageCode");

                    b.HasIndex("RoleId");

                    b.HasIndex("SpouseId");

                    b.HasIndex("SubdivisionId");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("RetirementTime.Domain.Entities.Location.Subdivision", b =>
                {
                    b.HasOne("RetirementTime.Domain.Entities.Location.Country", "Country")
                        .WithMany("Subdivisions")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("RetirementTime.Domain.Entities.Onboarding.OnboardingPersonalInfo", b =>
                {
                    b.HasOne("RetirementTime.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RetirementTime.Domain.Entities.RealEstate.BuyOrRent", b =>
                {
                    b.HasOne("RetirementTime.Domain.Entities.RealEstate.Mortgage", "Mortgage")
                        .WithMany()
                        .HasForeignKey("MortgageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RetirementTime.Domain.Entities.RealEstate.Rent", "Rent")
                        .WithMany()
                        .HasForeignKey("RentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mortgage");

                    b.Navigation("Rent");
                });

            modelBuilder.Entity("RetirementTime.Domain.Entities.RealEstate.Mortgage", b =>
                {
                    b.HasOne("RetirementTime.Domain.Entities.RealEstate.RealEstate", "RealEstate")
                        .WithMany()
                        .HasForeignKey("RealEstateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RealEstate");
                });

            modelBuilder.Entity("RetirementTime.Domain.Entities.User", b =>
                {
                    b.HasOne("RetirementTime.Domain.Entities.Location.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RetirementTime.Domain.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RetirementTime.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RetirementTime.Domain.Entities.User", "Spouse")
                        .WithMany()
                        .HasForeignKey("SpouseId");

                    b.HasOne("RetirementTime.Domain.Entities.Location.Subdivision", "Subdivision")
                        .WithMany()
                        .HasForeignKey("SubdivisionId");

                    b.Navigation("Country");

                    b.Navigation("Language");

                    b.Navigation("Role");

                    b.Navigation("Spouse");

                    b.Navigation("Subdivision");
                });

            modelBuilder.Entity("RetirementTime.Domain.Entities.Location.Country", b =>
                {
                    b.Navigation("Subdivisions");
                });

            modelBuilder.Entity("RetirementTime.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
