//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetirementTime.Resources.Dashboard {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DashboardResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DashboardResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("RetirementTime.Resources.Dashboard.DashboardResources", typeof(DashboardResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Home_Title {
            get {
                return ResourceManager.GetString("Home_Title", resourceCulture);
            }
        }
        
        public static string Home_Subtitle {
            get {
                return ResourceManager.GetString("Home_Subtitle", resourceCulture);
            }
        }
        
        public static string Home_Greeting {
            get {
                return ResourceManager.GetString("Home_Greeting", resourceCulture);
            }
        }
        
        public static string Home_Description {
            get {
                return ResourceManager.GetString("Home_Description", resourceCulture);
            }
        }
        
        public static string Home_Logout {
            get {
                return ResourceManager.GetString("Home_Logout", resourceCulture);
            }
        }
        
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        public static string Settings_IntroSection {
            get {
                return ResourceManager.GetString("Settings_IntroSection", resourceCulture);
            }
        }
        
        public static string Settings_ResetIntroLabel {
            get {
                return ResourceManager.GetString("Settings_ResetIntroLabel", resourceCulture);
            }
        }
        
        public static string Settings_ResetIntroDescription {
            get {
                return ResourceManager.GetString("Settings_ResetIntroDescription", resourceCulture);
            }
        }
        
        public static string Settings_ResetIntroButton {
            get {
                return ResourceManager.GetString("Settings_ResetIntroButton", resourceCulture);
            }
        }
        
        public static string Sidebar_Overview {
            get {
                return ResourceManager.GetString("Sidebar_Overview", resourceCulture);
            }
        }
        
        public static string Sidebar_ScenarioSettings {
            get {
                return ResourceManager.GetString("Sidebar_ScenarioSettings", resourceCulture);
            }
        }
        
        public static string Sidebar_FinancialProfile {
            get {
                return ResourceManager.GetString("Sidebar_FinancialProfile", resourceCulture);
            }
        }
        
        public static string Sidebar_Income {
            get {
                return ResourceManager.GetString("Sidebar_Income", resourceCulture);
            }
        }
        
        public static string Sidebar_Income_Employment {
            get {
                return ResourceManager.GetString("Sidebar_Income_Employment", resourceCulture);
            }
        }
        
        public static string Sidebar_Income_SelfEmployment {
            get {
                return ResourceManager.GetString("Sidebar_Income_SelfEmployment", resourceCulture);
            }
        }
        
        public static string Sidebar_Income_DefinedBenefits {
            get {
                return ResourceManager.GetString("Sidebar_Income_DefinedBenefits", resourceCulture);
            }
        }
        
        public static string Sidebar_Income_DefinedContribution {
            get {
                return ResourceManager.GetString("Sidebar_Income_DefinedContribution", resourceCulture);
            }
        }
        
        public static string Sidebar_Income_GroupRrsp {
            get {
                return ResourceManager.GetString("Sidebar_Income_GroupRrsp", resourceCulture);
            }
        }
        
        public static string Sidebar_Income_DefinedProfitSharing {
            get {
                return ResourceManager.GetString("Sidebar_Income_DefinedProfitSharing", resourceCulture);
            }
        }
        
        public static string Sidebar_Income_SharePurchasePlan {
            get {
                return ResourceManager.GetString("Sidebar_Income_SharePurchasePlan", resourceCulture);
            }
        }
        
        public static string Sidebar_Income_OasCpp {
            get {
                return ResourceManager.GetString("Sidebar_Income_OasCpp", resourceCulture);
            }
        }
        
        public static string Sidebar_Income_Other {
            get {
                return ResourceManager.GetString("Sidebar_Income_Other", resourceCulture);
            }
        }
        
        public static string Sidebar_Spending {
            get {
                return ResourceManager.GetString("Sidebar_Spending", resourceCulture);
            }
        }
        
        public static string Sidebar_NewScenario {
            get {
                return ResourceManager.GetString("Sidebar_NewScenario", resourceCulture);
            }
        }
        
        public static string Sidebar_Logout {
            get {
                return ResourceManager.GetString("Sidebar_Logout", resourceCulture);
            }
        }
        
        public static string Income_Title {
            get {
                return ResourceManager.GetString("Income_Title", resourceCulture);
            }
        }
        
        public static string Income_Subtitle {
            get {
                return ResourceManager.GetString("Income_Subtitle", resourceCulture);
            }
        }
        
        public static string Income_Next {
            get {
                return ResourceManager.GetString("Income_Next", resourceCulture);
            }
        }
        
        public static string Income_Employment_Title {
            get {
                return ResourceManager.GetString("Income_Employment_Title", resourceCulture);
            }
        }
        
        public static string Income_Employment_Subtitle {
            get {
                return ResourceManager.GetString("Income_Employment_Subtitle", resourceCulture);
            }
        }
        
        public static string Income_SelfEmployment_Title {
            get {
                return ResourceManager.GetString("Income_SelfEmployment_Title", resourceCulture);
            }
        }
        
        public static string Income_SelfEmployment_Subtitle {
            get {
                return ResourceManager.GetString("Income_SelfEmployment_Subtitle", resourceCulture);
            }
        }
        
        public static string Income_DefinedBenefits_Title {
            get {
                return ResourceManager.GetString("Income_DefinedBenefits_Title", resourceCulture);
            }
        }
        
        public static string Income_DefinedBenefits_Subtitle {
            get {
                return ResourceManager.GetString("Income_DefinedBenefits_Subtitle", resourceCulture);
            }
        }
        
        public static string Income_DefinedContribution_Title {
            get {
                return ResourceManager.GetString("Income_DefinedContribution_Title", resourceCulture);
            }
        }
        
        public static string Income_DefinedContribution_Subtitle {
            get {
                return ResourceManager.GetString("Income_DefinedContribution_Subtitle", resourceCulture);
            }
        }
        
        public static string Income_GroupRrsp_Title {
            get {
                return ResourceManager.GetString("Income_GroupRrsp_Title", resourceCulture);
            }
        }
        
        public static string Income_GroupRrsp_Subtitle {
            get {
                return ResourceManager.GetString("Income_GroupRrsp_Subtitle", resourceCulture);
            }
        }
        
        public static string Income_DefinedProfitSharing_Title {
            get {
                return ResourceManager.GetString("Income_DefinedProfitSharing_Title", resourceCulture);
            }
        }
        
        public static string Income_DefinedProfitSharing_Subtitle {
            get {
                return ResourceManager.GetString("Income_DefinedProfitSharing_Subtitle", resourceCulture);
            }
        }
        
        public static string Income_SharePurchasePlan_Title {
            get {
                return ResourceManager.GetString("Income_SharePurchasePlan_Title", resourceCulture);
            }
        }
        
        public static string Income_SharePurchasePlan_Subtitle {
            get {
                return ResourceManager.GetString("Income_SharePurchasePlan_Subtitle", resourceCulture);
            }
        }
        
        public static string Income_OasCpp_Title {
            get {
                return ResourceManager.GetString("Income_OasCpp_Title", resourceCulture);
            }
        }
        
        public static string Income_OasCpp_Subtitle {
            get {
                return ResourceManager.GetString("Income_OasCpp_Subtitle", resourceCulture);
            }
        }
        
        public static string Income_Other_Title {
            get {
                return ResourceManager.GetString("Income_Other_Title", resourceCulture);
            }
        }
        
        public static string Income_Other_Subtitle {
            get {
                return ResourceManager.GetString("Income_Other_Subtitle", resourceCulture);
            }
        }
        
        public static string Income_Remove {
            get {
                return ResourceManager.GetString("Income_Remove", resourceCulture);
            }
        }
        
        public static string Income_Employment_SectionTitle {
            get {
                return ResourceManager.GetString("Income_Employment_SectionTitle", resourceCulture);
            }
        }
        
        public static string Income_Employment_Hint {
            get {
                return ResourceManager.GetString("Income_Employment_Hint", resourceCulture);
            }
        }
        
        public static string Income_Employment_Item {
            get {
                return ResourceManager.GetString("Income_Employment_Item", resourceCulture);
            }
        }
        
        public static string Income_Employment_EmployerName {
            get {
                return ResourceManager.GetString("Income_Employment_EmployerName", resourceCulture);
            }
        }
        
        public static string Income_Employment_GrossSalary {
            get {
                return ResourceManager.GetString("Income_Employment_GrossSalary", resourceCulture);
            }
        }
        
        public static string Income_Employment_NetSalary {
            get {
                return ResourceManager.GetString("Income_Employment_NetSalary", resourceCulture);
            }
        }
        
        public static string Income_Employment_GrossCommissions {
            get {
                return ResourceManager.GetString("Income_Employment_GrossCommissions", resourceCulture);
            }
        }
        
        public static string Income_Employment_NetCommissions {
            get {
                return ResourceManager.GetString("Income_Employment_NetCommissions", resourceCulture);
            }
        }
        
        public static string Income_Employment_GrossBonus {
            get {
                return ResourceManager.GetString("Income_Employment_GrossBonus", resourceCulture);
            }
        }
        
        public static string Income_Employment_NetBonus {
            get {
                return ResourceManager.GetString("Income_Employment_NetBonus", resourceCulture);
            }
        }
        
        public static string Income_Employment_OtherIncome {
            get {
                return ResourceManager.GetString("Income_Employment_OtherIncome", resourceCulture);
            }
        }
        
        public static string Income_Employment_OtherIncomeName {
            get {
                return ResourceManager.GetString("Income_Employment_OtherIncomeName", resourceCulture);
            }
        }
        
        public static string Income_Employment_OtherIncomeGross {
            get {
                return ResourceManager.GetString("Income_Employment_OtherIncomeGross", resourceCulture);
            }
        }
        
        public static string Income_Employment_OtherIncomeNet {
            get {
                return ResourceManager.GetString("Income_Employment_OtherIncomeNet", resourceCulture);
            }
        }
        
        public static string Income_Employment_AddOtherIncome {
            get {
                return ResourceManager.GetString("Income_Employment_AddOtherIncome", resourceCulture);
            }
        }
        
        public static string Income_Employment_AddEmployment {
            get {
                return ResourceManager.GetString("Income_Employment_AddEmployment", resourceCulture);
            }
        }
    }
}
