//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetirementTime.Resources.Dashboard {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DashboardResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DashboardResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("RetirementTime.Resources.Dashboard.DashboardResources", typeof(DashboardResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Home_Title {
            get {
                return ResourceManager.GetString("Home_Title", resourceCulture);
            }
        }
        
        public static string Home_Subtitle {
            get {
                return ResourceManager.GetString("Home_Subtitle", resourceCulture);
            }
        }
        
        public static string Home_Greeting {
            get {
                return ResourceManager.GetString("Home_Greeting", resourceCulture);
            }
        }
        
        public static string Home_Description {
            get {
                return ResourceManager.GetString("Home_Description", resourceCulture);
            }
        }
        
        public static string Home_Logout {
            get {
                return ResourceManager.GetString("Home_Logout", resourceCulture);
            }
        }
        
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        public static string Settings_IntroSection {
            get {
                return ResourceManager.GetString("Settings_IntroSection", resourceCulture);
            }
        }
        
        public static string Settings_ResetIntroLabel {
            get {
                return ResourceManager.GetString("Settings_ResetIntroLabel", resourceCulture);
            }
        }
        
        public static string Settings_ResetIntroDescription {
            get {
                return ResourceManager.GetString("Settings_ResetIntroDescription", resourceCulture);
            }
        }
        
        public static string Settings_ResetIntroButton {
            get {
                return ResourceManager.GetString("Settings_ResetIntroButton", resourceCulture);
            }
        }
        
        public static string Sidebar_Overview {
            get {
                return ResourceManager.GetString("Sidebar_Overview", resourceCulture);
            }
        }
        
        public static string Sidebar_ScenarioSettings {
            get {
                return ResourceManager.GetString("Sidebar_ScenarioSettings", resourceCulture);
            }
        }
        
        public static string Sidebar_FinancialProfile {
            get {
                return ResourceManager.GetString("Sidebar_FinancialProfile", resourceCulture);
            }
        }
        
        public static string Sidebar_Income {
            get {
                return ResourceManager.GetString("Sidebar_Income", resourceCulture);
            }
        }
        
        public static string Sidebar_Income_Employment {
            get {
                return ResourceManager.GetString("Sidebar_Income_Employment", resourceCulture);
            }
        }
        
        public static string Sidebar_Income_SelfEmployment {
            get {
                return ResourceManager.GetString("Sidebar_Income_SelfEmployment", resourceCulture);
            }
        }
        
        public static string Sidebar_Income_DefinedBenefits {
            get {
                return ResourceManager.GetString("Sidebar_Income_DefinedBenefits", resourceCulture);
            }
        }
        
        public static string Sidebar_Income_DefinedContribution {
            get {
                return ResourceManager.GetString("Sidebar_Income_DefinedContribution", resourceCulture);
            }
        }
        
        public static string Sidebar_Income_GroupRrsp {
            get {
                return ResourceManager.GetString("Sidebar_Income_GroupRrsp", resourceCulture);
            }
        }
        
        public static string Sidebar_Income_DefinedProfitSharing {
            get {
                return ResourceManager.GetString("Sidebar_Income_DefinedProfitSharing", resourceCulture);
            }
        }
        
        public static string Sidebar_Income_SharePurchasePlan {
            get {
                return ResourceManager.GetString("Sidebar_Income_SharePurchasePlan", resourceCulture);
            }
        }
        
        public static string Sidebar_Income_OasCpp {
            get {
                return ResourceManager.GetString("Sidebar_Income_OasCpp", resourceCulture);
            }
        }
        
        public static string Sidebar_Income_Other {
            get {
                return ResourceManager.GetString("Sidebar_Income_Other", resourceCulture);
            }
        }
        
        public static string Sidebar_Spending {
            get {
                return ResourceManager.GetString("Sidebar_Spending", resourceCulture);
            }
        }
        
        public static string Sidebar_Spending_LivingExpenses {
            get {
                return ResourceManager.GetString("Sidebar_Spending_LivingExpenses", resourceCulture);
            }
        }
        
        public static string Sidebar_Spending_DiscretionaryExpenses {
            get {
                return ResourceManager.GetString("Sidebar_Spending_DiscretionaryExpenses", resourceCulture);
            }
        }
        
        public static string Sidebar_Spending_DebtRepayments {
            get {
                return ResourceManager.GetString("Sidebar_Spending_DebtRepayments", resourceCulture);
            }
        }
        
        public static string Sidebar_Spending_AssetsExpenses {
            get {
                return ResourceManager.GetString("Sidebar_Spending_AssetsExpenses", resourceCulture);
            }
        }
        
        public static string Sidebar_Spending_OtherExpenses {
            get {
                return ResourceManager.GetString("Sidebar_Spending_OtherExpenses", resourceCulture);
            }
        }
        
        public static string Sidebar_NewScenario {
            get {
                return ResourceManager.GetString("Sidebar_NewScenario", resourceCulture);
            }
        }
        
        public static string Sidebar_NetWorth {
            get {
                return ResourceManager.GetString("Sidebar_NetWorth", resourceCulture);
            }
        }
        
        public static string Sidebar_ScenarioOverview {
            get {
                return ResourceManager.GetString("Sidebar_ScenarioOverview", resourceCulture);
            }
        }
        
        public static string Sidebar_Cashflow {
            get {
                return ResourceManager.GetString("Sidebar_Cashflow", resourceCulture);
            }
        }
        
        public static string NetWorth_Title {
            get {
                return ResourceManager.GetString("NetWorth_Title", resourceCulture);
            }
        }
        
        public static string NetWorth_Subtitle {
            get {
                return ResourceManager.GetString("NetWorth_Subtitle", resourceCulture);
            }
        }
        
        public static string NetWorth_ConsolidatedValue {
            get {
                return ResourceManager.GetString("NetWorth_ConsolidatedValue", resourceCulture);
            }
        }
        
        public static string NetWorth_Category_RealEstate {
            get {
                return ResourceManager.GetString("NetWorth_Category_RealEstate", resourceCulture);
            }
        }
        
        public static string NetWorth_Category_Investments {
            get {
                return ResourceManager.GetString("NetWorth_Category_Investments", resourceCulture);
            }
        }
        
        public static string NetWorth_Category_PhysicalAssets {
            get {
                return ResourceManager.GetString("NetWorth_Category_PhysicalAssets", resourceCulture);
            }
        }
        
        public static string NetWorth_Category_TotalDebts {
            get {
                return ResourceManager.GetString("NetWorth_Category_TotalDebts", resourceCulture);
            }
        }
        
        public static string NetWorth_GrowthProjection_Title {
            get {
                return ResourceManager.GetString("NetWorth_GrowthProjection_Title", resourceCulture);
            }
        }
        
        public static string NetWorth_GrowthProjection_Subtitle {
            get {
                return ResourceManager.GetString("NetWorth_GrowthProjection_Subtitle", resourceCulture);
            }
        }
        
        public static string NetWorth_Legend_NetWorth {
            get {
                return ResourceManager.GetString("NetWorth_Legend_NetWorth", resourceCulture);
            }
        }
        
        public static string NetWorth_Legend_Liabilities {
            get {
                return ResourceManager.GetString("NetWorth_Legend_Liabilities", resourceCulture);
            }
        }
        
        public static string NetWorth_BalanceSheet_Title {
            get {
                return ResourceManager.GetString("NetWorth_BalanceSheet_Title", resourceCulture);
            }
        }
        
        public static string NetWorth_Col_Name {
            get {
                return ResourceManager.GetString("NetWorth_Col_Name", resourceCulture);
            }
        }
        
        public static string NetWorth_Col_Type {
            get {
                return ResourceManager.GetString("NetWorth_Col_Type", resourceCulture);
            }
        }
        
        public static string NetWorth_Col_Value {
            get {
                return ResourceManager.GetString("NetWorth_Col_Value", resourceCulture);
            }
        }
        
        public static string NetWorth_Col_DebtAgainst {
            get {
                return ResourceManager.GetString("NetWorth_Col_DebtAgainst", resourceCulture);
            }
        }
        
        public static string NetWorth_Type_Home {
            get {
                return ResourceManager.GetString("NetWorth_Type_Home", resourceCulture);
            }
        }
        
        public static string NetWorth_Type_InvestmentProperty {
            get {
                return ResourceManager.GetString("NetWorth_Type_InvestmentProperty", resourceCulture);
            }
        }
        
        public static string NetWorth_Type_InvestmentAccount {
            get {
                return ResourceManager.GetString("NetWorth_Type_InvestmentAccount", resourceCulture);
            }
        }
        
        public static string NetWorth_Type_PhysicalAsset {
            get {
                return ResourceManager.GetString("NetWorth_Type_PhysicalAsset", resourceCulture);
            }
        }
        
        public static string Sidebar_Logout {
            get {
                return ResourceManager.GetString("Sidebar_Logout", resourceCulture);
            }
        }
        
        public static string Income_Title {
            get {
                return ResourceManager.GetString("Income_Title", resourceCulture);
            }
        }
        
        public static string Income_Subtitle {
            get {
                return ResourceManager.GetString("Income_Subtitle", resourceCulture);
            }
        }
        
        public static string Income_Next {
            get {
                return ResourceManager.GetString("Income_Next", resourceCulture);
            }
        }
        
        public static string Income_Employment_Title {
            get {
                return ResourceManager.GetString("Income_Employment_Title", resourceCulture);
            }
        }
        
        public static string Income_Employment_Subtitle {
            get {
                return ResourceManager.GetString("Income_Employment_Subtitle", resourceCulture);
            }
        }
        
        public static string Income_SelfEmployment_Title {
            get {
                return ResourceManager.GetString("Income_SelfEmployment_Title", resourceCulture);
            }
        }
        
        public static string Income_SelfEmployment_Subtitle {
            get {
                return ResourceManager.GetString("Income_SelfEmployment_Subtitle", resourceCulture);
            }
        }
        
        public static string Income_DefinedBenefits_Title {
            get {
                return ResourceManager.GetString("Income_DefinedBenefits_Title", resourceCulture);
            }
        }
        
        public static string Income_DefinedBenefits_Subtitle {
            get {
                return ResourceManager.GetString("Income_DefinedBenefits_Subtitle", resourceCulture);
            }
        }
        
        public static string Income_DefinedContribution_Title {
            get {
                return ResourceManager.GetString("Income_DefinedContribution_Title", resourceCulture);
            }
        }
        
        public static string Income_DefinedContribution_Subtitle {
            get {
                return ResourceManager.GetString("Income_DefinedContribution_Subtitle", resourceCulture);
            }
        }
        
        public static string Income_GroupRrsp_Title {
            get {
                return ResourceManager.GetString("Income_GroupRrsp_Title", resourceCulture);
            }
        }
        
        public static string Income_GroupRrsp_Subtitle {
            get {
                return ResourceManager.GetString("Income_GroupRrsp_Subtitle", resourceCulture);
            }
        }
        
        public static string Income_DefinedProfitSharing_Title {
            get {
                return ResourceManager.GetString("Income_DefinedProfitSharing_Title", resourceCulture);
            }
        }
        
        public static string Income_DefinedProfitSharing_Subtitle {
            get {
                return ResourceManager.GetString("Income_DefinedProfitSharing_Subtitle", resourceCulture);
            }
        }
        
        public static string Income_SharePurchasePlan_Title {
            get {
                return ResourceManager.GetString("Income_SharePurchasePlan_Title", resourceCulture);
            }
        }
        
        public static string Income_SharePurchasePlan_Subtitle {
            get {
                return ResourceManager.GetString("Income_SharePurchasePlan_Subtitle", resourceCulture);
            }
        }
        
        public static string Income_OasCpp_Title {
            get {
                return ResourceManager.GetString("Income_OasCpp_Title", resourceCulture);
            }
        }
        
        public static string Income_OasCpp_Subtitle {
            get {
                return ResourceManager.GetString("Income_OasCpp_Subtitle", resourceCulture);
            }
        }
        
        public static string Income_Other_Title {
            get {
                return ResourceManager.GetString("Income_Other_Title", resourceCulture);
            }
        }
        
        public static string Income_Other_Subtitle {
            get {
                return ResourceManager.GetString("Income_Other_Subtitle", resourceCulture);
            }
        }
        
        public static string Income_Remove {
            get {
                return ResourceManager.GetString("Income_Remove", resourceCulture);
            }
        }
        
        public static string Income_Employment_SectionTitle {
            get {
                return ResourceManager.GetString("Income_Employment_SectionTitle", resourceCulture);
            }
        }
        
        public static string Income_Employment_Hint {
            get {
                return ResourceManager.GetString("Income_Employment_Hint", resourceCulture);
            }
        }
        
        public static string Income_Employment_Item {
            get {
                return ResourceManager.GetString("Income_Employment_Item", resourceCulture);
            }
        }
        
        public static string Income_Employment_EmployerName {
            get {
                return ResourceManager.GetString("Income_Employment_EmployerName", resourceCulture);
            }
        }
        
        public static string Income_Employment_GrossSalary {
            get {
                return ResourceManager.GetString("Income_Employment_GrossSalary", resourceCulture);
            }
        }
        
        public static string Income_Employment_NetSalary {
            get {
                return ResourceManager.GetString("Income_Employment_NetSalary", resourceCulture);
            }
        }
        
        public static string Income_Employment_GrossCommissions {
            get {
                return ResourceManager.GetString("Income_Employment_GrossCommissions", resourceCulture);
            }
        }
        
        public static string Income_Employment_NetCommissions {
            get {
                return ResourceManager.GetString("Income_Employment_NetCommissions", resourceCulture);
            }
        }
        
        public static string Income_Employment_GrossBonus {
            get {
                return ResourceManager.GetString("Income_Employment_GrossBonus", resourceCulture);
            }
        }
        
        public static string Income_Employment_NetBonus {
            get {
                return ResourceManager.GetString("Income_Employment_NetBonus", resourceCulture);
            }
        }
        
        public static string Income_Employment_OtherIncome {
            get {
                return ResourceManager.GetString("Income_Employment_OtherIncome", resourceCulture);
            }
        }
        
        public static string Income_Employment_OtherIncomeName {
            get {
                return ResourceManager.GetString("Income_Employment_OtherIncomeName", resourceCulture);
            }
        }
        
        public static string Income_Employment_OtherIncomeGross {
            get {
                return ResourceManager.GetString("Income_Employment_OtherIncomeGross", resourceCulture);
            }
        }
        
        public static string Income_Employment_OtherIncomeNet {
            get {
                return ResourceManager.GetString("Income_Employment_OtherIncomeNet", resourceCulture);
            }
        }
        
        public static string Income_Employment_AddOtherIncome {
            get {
                return ResourceManager.GetString("Income_Employment_AddOtherIncome", resourceCulture);
            }
        }
        
        public static string Income_Employment_AddEmployment {
            get {
                return ResourceManager.GetString("Income_Employment_AddEmployment", resourceCulture);
            }
        }
        
        public static string Income_SelfEmployment_SectionTitle {
            get {
                return ResourceManager.GetString("Income_SelfEmployment_SectionTitle", resourceCulture);
            }
        }
        
        public static string Income_SelfEmployment_Hint {
            get {
                return ResourceManager.GetString("Income_SelfEmployment_Hint", resourceCulture);
            }
        }
        
        public static string Income_SelfEmployment_Item {
            get {
                return ResourceManager.GetString("Income_SelfEmployment_Item", resourceCulture);
            }
        }
        
        public static string Income_SelfEmployment_Name {
            get {
                return ResourceManager.GetString("Income_SelfEmployment_Name", resourceCulture);
            }
        }
        
        public static string Income_SelfEmployment_GrossSalary {
            get {
                return ResourceManager.GetString("Income_SelfEmployment_GrossSalary", resourceCulture);
            }
        }
        
        public static string Income_SelfEmployment_NetSalary {
            get {
                return ResourceManager.GetString("Income_SelfEmployment_NetSalary", resourceCulture);
            }
        }
        
        public static string Income_SelfEmployment_GrossDividends {
            get {
                return ResourceManager.GetString("Income_SelfEmployment_GrossDividends", resourceCulture);
            }
        }
        
        public static string Income_SelfEmployment_NetDividends {
            get {
                return ResourceManager.GetString("Income_SelfEmployment_NetDividends", resourceCulture);
            }
        }
        
        public static string Income_SelfEmployment_AddSelfEmployment {
            get {
                return ResourceManager.GetString("Income_SelfEmployment_AddSelfEmployment", resourceCulture);
            }
        }
        
        public static string Income_DefinedBenefits_SectionTitle {
            get {
                return ResourceManager.GetString("Income_DefinedBenefits_SectionTitle", resourceCulture);
            }
        }
        
        public static string Income_DefinedBenefits_Hint {
            get {
                return ResourceManager.GetString("Income_DefinedBenefits_Hint", resourceCulture);
            }
        }
        
        public static string Income_DefinedBenefits_Item {
            get {
                return ResourceManager.GetString("Income_DefinedBenefits_Item", resourceCulture);
            }
        }
        
        public static string Income_DefinedBenefits_Name {
            get {
                return ResourceManager.GetString("Income_DefinedBenefits_Name", resourceCulture);
            }
        }
        
        public static string Income_DefinedBenefits_StartAge {
            get {
                return ResourceManager.GetString("Income_DefinedBenefits_StartAge", resourceCulture);
            }
        }
        
        public static string Income_DefinedBenefits_BenefitsPre65 {
            get {
                return ResourceManager.GetString("Income_DefinedBenefits_BenefitsPre65", resourceCulture);
            }
        }
        
        public static string Income_DefinedBenefits_BenefitsPost65 {
            get {
                return ResourceManager.GetString("Income_DefinedBenefits_BenefitsPost65", resourceCulture);
            }
        }
        
        public static string Income_DefinedBenefits_PercentIndexedToInflation {
            get {
                return ResourceManager.GetString("Income_DefinedBenefits_PercentIndexedToInflation", resourceCulture);
            }
        }
        
        public static string Income_DefinedBenefits_PercentSurvivorBenefits {
            get {
                return ResourceManager.GetString("Income_DefinedBenefits_PercentSurvivorBenefits", resourceCulture);
            }
        }
        
        public static string Income_DefinedBenefits_RrspAdjustment {
            get {
                return ResourceManager.GetString("Income_DefinedBenefits_RrspAdjustment", resourceCulture);
            }
        }
        
        public static string Income_DefinedBenefits_AddPension {
            get {
                return ResourceManager.GetString("Income_DefinedBenefits_AddPension", resourceCulture);
            }
        }
        
        public static string Income_DefinedContribution_SectionTitle {
            get {
                return ResourceManager.GetString("Income_DefinedContribution_SectionTitle", resourceCulture);
            }
        }
        
        public static string Income_DefinedContribution_Hint {
            get {
                return ResourceManager.GetString("Income_DefinedContribution_Hint", resourceCulture);
            }
        }
        
        public static string Income_DefinedContribution_Item {
            get {
                return ResourceManager.GetString("Income_DefinedContribution_Item", resourceCulture);
            }
        }
        
        public static string Income_DefinedContribution_Name {
            get {
                return ResourceManager.GetString("Income_DefinedContribution_Name", resourceCulture);
            }
        }
        
        public static string Income_DefinedContribution_PercentEmployee {
            get {
                return ResourceManager.GetString("Income_DefinedContribution_PercentEmployee", resourceCulture);
            }
        }
        
        public static string Income_DefinedContribution_PercentEmployer {
            get {
                return ResourceManager.GetString("Income_DefinedContribution_PercentEmployer", resourceCulture);
            }
        }
        
        public static string Income_DefinedContribution_AddPlan {
            get {
                return ResourceManager.GetString("Income_DefinedContribution_AddPlan", resourceCulture);
            }
        }
        
        public static string Income_DefinedProfitSharing_SectionTitle {
            get {
                return ResourceManager.GetString("Income_DefinedProfitSharing_SectionTitle", resourceCulture);
            }
        }
        
        public static string Income_DefinedProfitSharing_Hint {
            get {
                return ResourceManager.GetString("Income_DefinedProfitSharing_Hint", resourceCulture);
            }
        }
        
        public static string Income_DefinedProfitSharing_Item {
            get {
                return ResourceManager.GetString("Income_DefinedProfitSharing_Item", resourceCulture);
            }
        }
        
        public static string Income_DefinedProfitSharing_Name {
            get {
                return ResourceManager.GetString("Income_DefinedProfitSharing_Name", resourceCulture);
            }
        }
        
        public static string Income_DefinedProfitSharing_PercentEmployer {
            get {
                return ResourceManager.GetString("Income_DefinedProfitSharing_PercentEmployer", resourceCulture);
            }
        }
        
        public static string Income_DefinedProfitSharing_AddPlan {
            get {
                return ResourceManager.GetString("Income_DefinedProfitSharing_AddPlan", resourceCulture);
            }
        }
        
        public static string Income_GroupRrsp_SectionTitle {
            get {
                return ResourceManager.GetString("Income_GroupRrsp_SectionTitle", resourceCulture);
            }
        }
        
        public static string Income_GroupRrsp_Hint {
            get {
                return ResourceManager.GetString("Income_GroupRrsp_Hint", resourceCulture);
            }
        }
        
        public static string Income_GroupRrsp_Item {
            get {
                return ResourceManager.GetString("Income_GroupRrsp_Item", resourceCulture);
            }
        }
        
        public static string Income_GroupRrsp_Name {
            get {
                return ResourceManager.GetString("Income_GroupRrsp_Name", resourceCulture);
            }
        }
        
        public static string Income_GroupRrsp_PercentEmployee {
            get {
                return ResourceManager.GetString("Income_GroupRrsp_PercentEmployee", resourceCulture);
            }
        }
        
        public static string Income_GroupRrsp_PercentEmployer {
            get {
                return ResourceManager.GetString("Income_GroupRrsp_PercentEmployer", resourceCulture);
            }
        }
        
        public static string Income_GroupRrsp_AddPlan {
            get {
                return ResourceManager.GetString("Income_GroupRrsp_AddPlan", resourceCulture);
            }
        }
        
        public static string Income_SharePurchasePlan_SectionTitle {
            get {
                return ResourceManager.GetString("Income_SharePurchasePlan_SectionTitle", resourceCulture);
            }
        }
        
        public static string Income_SharePurchasePlan_Hint {
            get {
                return ResourceManager.GetString("Income_SharePurchasePlan_Hint", resourceCulture);
            }
        }
        
        public static string Income_SharePurchasePlan_Item {
            get {
                return ResourceManager.GetString("Income_SharePurchasePlan_Item", resourceCulture);
            }
        }
        
        public static string Income_SharePurchasePlan_Name {
            get {
                return ResourceManager.GetString("Income_SharePurchasePlan_Name", resourceCulture);
            }
        }
        
        public static string Income_SharePurchasePlan_PercentEmployee {
            get {
                return ResourceManager.GetString("Income_SharePurchasePlan_PercentEmployee", resourceCulture);
            }
        }
        
        public static string Income_SharePurchasePlan_PercentEmployer {
            get {
                return ResourceManager.GetString("Income_SharePurchasePlan_PercentEmployer", resourceCulture);
            }
        }
        
        public static string Income_SharePurchasePlan_UseFlatAmount {
            get {
                return ResourceManager.GetString("Income_SharePurchasePlan_UseFlatAmount", resourceCulture);
            }
        }
        
        public static string Income_SharePurchasePlan_AddPlan {
            get {
                return ResourceManager.GetString("Income_SharePurchasePlan_AddPlan", resourceCulture);
            }
        }
        
        public static string Income_OasCpp_SectionTitle {
            get {
                return ResourceManager.GetString("Income_OasCpp_SectionTitle", resourceCulture);
            }
        }
        
        public static string Income_OasCpp_Hint {
            get {
                return ResourceManager.GetString("Income_OasCpp_Hint", resourceCulture);
            }
        }
        
        public static string Income_OasCpp_IncomeLastYear {
            get {
                return ResourceManager.GetString("Income_OasCpp_IncomeLastYear", resourceCulture);
            }
        }
        
        public static string Income_OasCpp_Income2YearsAgo {
            get {
                return ResourceManager.GetString("Income_OasCpp_Income2YearsAgo", resourceCulture);
            }
        }
        
        public static string Income_OasCpp_Income3YearsAgo {
            get {
                return ResourceManager.GetString("Income_OasCpp_Income3YearsAgo", resourceCulture);
            }
        }
        
        public static string Income_OasCpp_Income4YearsAgo {
            get {
                return ResourceManager.GetString("Income_OasCpp_Income4YearsAgo", resourceCulture);
            }
        }
        
        public static string Income_OasCpp_Income5YearsAgo {
            get {
                return ResourceManager.GetString("Income_OasCpp_Income5YearsAgo", resourceCulture);
            }
        }
        
        public static string Income_OasCpp_YearsSpentInCanada {
            get {
                return ResourceManager.GetString("Income_OasCpp_YearsSpentInCanada", resourceCulture);
            }
        }
        
        public static string Income_Other_SectionTitle {
            get {
                return ResourceManager.GetString("Income_Other_SectionTitle", resourceCulture);
            }
        }
        
        public static string Income_Other_Hint {
            get {
                return ResourceManager.GetString("Income_Other_Hint", resourceCulture);
            }
        }
        
        public static string Income_Other_Item {
            get {
                return ResourceManager.GetString("Income_Other_Item", resourceCulture);
            }
        }
        
        public static string Income_Other_Name {
            get {
                return ResourceManager.GetString("Income_Other_Name", resourceCulture);
            }
        }
        
        public static string Income_Other_Amount {
            get {
                return ResourceManager.GetString("Income_Other_Amount", resourceCulture);
            }
        }
        
        public static string Income_Other_AddIncome {
            get {
                return ResourceManager.GetString("Income_Other_AddIncome", resourceCulture);
            }
        }
        
        public static string Sidebar_Assets {
            get {
                return ResourceManager.GetString("Sidebar_Assets", resourceCulture);
            }
        }
        
        public static string Sidebar_Assets_Home {
            get {
                return ResourceManager.GetString("Sidebar_Assets_Home", resourceCulture);
            }
        }
        
        public static string Sidebar_Assets_InvestmentProperties {
            get {
                return ResourceManager.GetString("Sidebar_Assets_InvestmentProperties", resourceCulture);
            }
        }
        
        public static string Assets_Home_Title {
            get {
                return ResourceManager.GetString("Assets_Home_Title", resourceCulture);
            }
        }
        
        public static string Assets_Home_Subtitle {
            get {
                return ResourceManager.GetString("Assets_Home_Subtitle", resourceCulture);
            }
        }
        
        public static string Assets_Home_SectionTitle {
            get {
                return ResourceManager.GetString("Assets_Home_SectionTitle", resourceCulture);
            }
        }
        
        public static string Assets_Home_Hint {
            get {
                return ResourceManager.GetString("Assets_Home_Hint", resourceCulture);
            }
        }
        
        public static string Assets_Home_PurchaseDate {
            get {
                return ResourceManager.GetString("Assets_Home_PurchaseDate", resourceCulture);
            }
        }
        
        public static string Assets_Home_HomeValue {
            get {
                return ResourceManager.GetString("Assets_Home_HomeValue", resourceCulture);
            }
        }
        
        public static string Assets_Home_PurchasePrice {
            get {
                return ResourceManager.GetString("Assets_Home_PurchasePrice", resourceCulture);
            }
        }
        
        public static string Assets_InvestmentProperties_Title {
            get {
                return ResourceManager.GetString("Assets_InvestmentProperties_Title", resourceCulture);
            }
        }
        
        public static string Assets_InvestmentProperties_Subtitle {
            get {
                return ResourceManager.GetString("Assets_InvestmentProperties_Subtitle", resourceCulture);
            }
        }
        
        public static string Assets_InvestmentProperties_SectionTitle {
            get {
                return ResourceManager.GetString("Assets_InvestmentProperties_SectionTitle", resourceCulture);
            }
        }
        
        public static string Assets_InvestmentProperties_Hint {
            get {
                return ResourceManager.GetString("Assets_InvestmentProperties_Hint", resourceCulture);
            }
        }
        
        public static string Assets_InvestmentProperties_Item {
            get {
                return ResourceManager.GetString("Assets_InvestmentProperties_Item", resourceCulture);
            }
        }
        
        public static string Assets_InvestmentProperties_Name {
            get {
                return ResourceManager.GetString("Assets_InvestmentProperties_Name", resourceCulture);
            }
        }
        
        public static string Assets_InvestmentProperties_PurchaseDate {
            get {
                return ResourceManager.GetString("Assets_InvestmentProperties_PurchaseDate", resourceCulture);
            }
        }
        
        public static string Assets_InvestmentProperties_PropertyValue {
            get {
                return ResourceManager.GetString("Assets_InvestmentProperties_PropertyValue", resourceCulture);
            }
        }
        
        public static string Assets_InvestmentProperties_PurchasePrice {
            get {
                return ResourceManager.GetString("Assets_InvestmentProperties_PurchasePrice", resourceCulture);
            }
        }
        
        public static string Assets_InvestmentProperties_AddProperty {
            get {
                return ResourceManager.GetString("Assets_InvestmentProperties_AddProperty", resourceCulture);
            }
        }
        
        public static string Assets_Next {
            get {
                return ResourceManager.GetString("Assets_Next", resourceCulture);
            }
        }
        
        public static string Assets_Remove {
            get {
                return ResourceManager.GetString("Assets_Remove", resourceCulture);
            }
        }
        
        public static string Sidebar_Assets_InvestmentAccounts {
            get {
                return ResourceManager.GetString("Sidebar_Assets_InvestmentAccounts", resourceCulture);
            }
        }
        
        public static string Sidebar_Assets_PhysicalAssets {
            get {
                return ResourceManager.GetString("Sidebar_Assets_PhysicalAssets", resourceCulture);
            }
        }
        
        public static string Assets_InvestmentAccounts_Title {
            get {
                return ResourceManager.GetString("Assets_InvestmentAccounts_Title", resourceCulture);
            }
        }
        
        public static string Assets_InvestmentAccounts_Subtitle {
            get {
                return ResourceManager.GetString("Assets_InvestmentAccounts_Subtitle", resourceCulture);
            }
        }
        
        public static string Assets_InvestmentAccounts_SectionTitle {
            get {
                return ResourceManager.GetString("Assets_InvestmentAccounts_SectionTitle", resourceCulture);
            }
        }
        
        public static string Assets_InvestmentAccounts_Hint {
            get {
                return ResourceManager.GetString("Assets_InvestmentAccounts_Hint", resourceCulture);
            }
        }
        
        public static string Assets_InvestmentAccounts_Item {
            get {
                return ResourceManager.GetString("Assets_InvestmentAccounts_Item", resourceCulture);
            }
        }
        
        public static string Assets_InvestmentAccounts_AccountName {
            get {
                return ResourceManager.GetString("Assets_InvestmentAccounts_AccountName", resourceCulture);
            }
        }
        
        public static string Assets_InvestmentAccounts_AccountType {
            get {
                return ResourceManager.GetString("Assets_InvestmentAccounts_AccountType", resourceCulture);
            }
        }
        
        public static string Assets_InvestmentAccounts_AdjustedCostBasis {
            get {
                return ResourceManager.GetString("Assets_InvestmentAccounts_AdjustedCostBasis", resourceCulture);
            }
        }
        
        public static string Assets_InvestmentAccounts_TotalValue {
            get {
                return ResourceManager.GetString("Assets_InvestmentAccounts_TotalValue", resourceCulture);
            }
        }
        
        public static string Assets_InvestmentAccounts_UseIndividualHoldings {
            get {
                return ResourceManager.GetString("Assets_InvestmentAccounts_UseIndividualHoldings", resourceCulture);
            }
        }
        
        public static string Assets_InvestmentAccounts_AddAccount {
            get {
                return ResourceManager.GetString("Assets_InvestmentAccounts_AddAccount", resourceCulture);
            }
        }
        
        public static string Assets_InvestmentAccounts_Holdings_SectionLabel {
            get {
                return ResourceManager.GetString("Assets_InvestmentAccounts_Holdings_SectionLabel", resourceCulture);
            }
        }
        
        public static string Assets_InvestmentAccounts_Holdings_AssetName {
            get {
                return ResourceManager.GetString("Assets_InvestmentAccounts_Holdings_AssetName", resourceCulture);
            }
        }
        
        public static string Assets_InvestmentAccounts_Holdings_IsPubliclyTraded {
            get {
                return ResourceManager.GetString("Assets_InvestmentAccounts_Holdings_IsPubliclyTraded", resourceCulture);
            }
        }
        
        public static string Assets_InvestmentAccounts_Holdings_CurrentValue {
            get {
                return ResourceManager.GetString("Assets_InvestmentAccounts_Holdings_CurrentValue", resourceCulture);
            }
        }
        
        public static string Assets_InvestmentAccounts_Holdings_TickerSymbol {
            get {
                return ResourceManager.GetString("Assets_InvestmentAccounts_Holdings_TickerSymbol", resourceCulture);
            }
        }
        
        public static string Assets_InvestmentAccounts_Holdings_AdjustedCostBasis {
            get {
                return ResourceManager.GetString("Assets_InvestmentAccounts_Holdings_AdjustedCostBasis", resourceCulture);
            }
        }
        
        public static string Assets_InvestmentAccounts_Holdings_AddHolding {
            get {
                return ResourceManager.GetString("Assets_InvestmentAccounts_Holdings_AddHolding", resourceCulture);
            }
        }
        
        public static string Assets_PhysicalAssets_Title {
            get {
                return ResourceManager.GetString("Assets_PhysicalAssets_Title", resourceCulture);
            }
        }
        
        public static string Assets_PhysicalAssets_Subtitle {
            get {
                return ResourceManager.GetString("Assets_PhysicalAssets_Subtitle", resourceCulture);
            }
        }
        
        public static string Assets_PhysicalAssets_SectionTitle {
            get {
                return ResourceManager.GetString("Assets_PhysicalAssets_SectionTitle", resourceCulture);
            }
        }
        
        public static string Assets_PhysicalAssets_Hint {
            get {
                return ResourceManager.GetString("Assets_PhysicalAssets_Hint", resourceCulture);
            }
        }
        
        public static string Assets_PhysicalAssets_Item {
            get {
                return ResourceManager.GetString("Assets_PhysicalAssets_Item", resourceCulture);
            }
        }
        
        public static string Assets_PhysicalAssets_Name {
            get {
                return ResourceManager.GetString("Assets_PhysicalAssets_Name", resourceCulture);
            }
        }
        
        public static string Assets_PhysicalAssets_AssetType {
            get {
                return ResourceManager.GetString("Assets_PhysicalAssets_AssetType", resourceCulture);
            }
        }
        
        public static string Assets_PhysicalAssets_EstimatedValue {
            get {
                return ResourceManager.GetString("Assets_PhysicalAssets_EstimatedValue", resourceCulture);
            }
        }
        
        public static string Assets_PhysicalAssets_AdjustedCostBasis {
            get {
                return ResourceManager.GetString("Assets_PhysicalAssets_AdjustedCostBasis", resourceCulture);
            }
        }
        
        public static string Assets_PhysicalAssets_IsPersonalProperty {
            get {
                return ResourceManager.GetString("Assets_PhysicalAssets_IsPersonalProperty", resourceCulture);
            }
        }
        
        public static string Assets_PhysicalAssets_IsRetirementAsset {
            get {
                return ResourceManager.GetString("Assets_PhysicalAssets_IsRetirementAsset", resourceCulture);
            }
        }
        
        public static string Assets_PhysicalAssets_AddAsset {
            get {
                return ResourceManager.GetString("Assets_PhysicalAssets_AddAsset", resourceCulture);
            }
        }
        
        public static string Sidebar_Debt {
            get {
                return ResourceManager.GetString("Sidebar_Debt", resourceCulture);
            }
        }
        
        public static string Sidebar_Debt_HomeMortgage {
            get {
                return ResourceManager.GetString("Sidebar_Debt_HomeMortgage", resourceCulture);
            }
        }
        
        public static string Sidebar_Debt_InvestmentPropertyMortgage {
            get {
                return ResourceManager.GetString("Sidebar_Debt_InvestmentPropertyMortgage", resourceCulture);
            }
        }
        
        public static string Sidebar_Debt_CarLoans {
            get {
                return ResourceManager.GetString("Sidebar_Debt_CarLoans", resourceCulture);
            }
        }
        
        public static string Sidebar_Debt_StudentLoans {
            get {
                return ResourceManager.GetString("Sidebar_Debt_StudentLoans", resourceCulture);
            }
        }
        
        public static string Sidebar_Debt_MedicalDebt {
            get {
                return ResourceManager.GetString("Sidebar_Debt_MedicalDebt", resourceCulture);
            }
        }
        
        public static string Sidebar_Debt_PersonalLoans {
            get {
                return ResourceManager.GetString("Sidebar_Debt_PersonalLoans", resourceCulture);
            }
        }
        
        public static string Sidebar_Debt_CreditCards {
            get {
                return ResourceManager.GetString("Sidebar_Debt_CreditCards", resourceCulture);
            }
        }
        
        public static string Debt_Next {
            get {
                return ResourceManager.GetString("Debt_Next", resourceCulture);
            }
        }
        
        public static string Debt_Remove {
            get {
                return ResourceManager.GetString("Debt_Remove", resourceCulture);
            }
        }
        
        public static string Debt_HomeMortgage_Title {
            get {
                return ResourceManager.GetString("Debt_HomeMortgage_Title", resourceCulture);
            }
        }
        
        public static string Debt_HomeMortgage_Subtitle {
            get {
                return ResourceManager.GetString("Debt_HomeMortgage_Subtitle", resourceCulture);
            }
        }
        
        public static string Debt_HomeMortgage_SectionTitle {
            get {
                return ResourceManager.GetString("Debt_HomeMortgage_SectionTitle", resourceCulture);
            }
        }
        
        public static string Debt_HomeMortgage_Principal {
            get {
                return ResourceManager.GetString("Debt_HomeMortgage_Principal", resourceCulture);
            }
        }
        
        public static string Debt_HomeMortgage_InterestRate {
            get {
                return ResourceManager.GetString("Debt_HomeMortgage_InterestRate", resourceCulture);
            }
        }
        
        public static string Debt_HomeMortgage_Frequency {
            get {
                return ResourceManager.GetString("Debt_HomeMortgage_Frequency", resourceCulture);
            }
        }
        
        public static string Debt_HomeMortgage_TermInYears {
            get {
                return ResourceManager.GetString("Debt_HomeMortgage_TermInYears", resourceCulture);
            }
        }
        
        public static string Debt_InvestmentProperty_Title {
            get {
                return ResourceManager.GetString("Debt_InvestmentProperty_Title", resourceCulture);
            }
        }
        
        public static string Debt_InvestmentProperty_Subtitle {
            get {
                return ResourceManager.GetString("Debt_InvestmentProperty_Subtitle", resourceCulture);
            }
        }
        
        public static string Debt_InvestmentProperty_SectionTitle {
            get {
                return ResourceManager.GetString("Debt_InvestmentProperty_SectionTitle", resourceCulture);
            }
        }
        
        public static string Debt_InvestmentProperty_Hint {
            get {
                return ResourceManager.GetString("Debt_InvestmentProperty_Hint", resourceCulture);
            }
        }
        
        public static string Debt_InvestmentProperty_Item {
            get {
                return ResourceManager.GetString("Debt_InvestmentProperty_Item", resourceCulture);
            }
        }
        
        public static string Debt_InvestmentProperty_AddItem {
            get {
                return ResourceManager.GetString("Debt_InvestmentProperty_AddItem", resourceCulture);
            }
        }
        
        public static string Debt_InvestmentProperty_DefaultName {
            get {
                return ResourceManager.GetString("Debt_InvestmentProperty_DefaultName", resourceCulture);
            }
        }
        
        public static string Debt_StudentLoans_Title {
            get {
                return ResourceManager.GetString("Debt_StudentLoans_Title", resourceCulture);
            }
        }
        
        public static string Debt_StudentLoans_Subtitle {
            get {
                return ResourceManager.GetString("Debt_StudentLoans_Subtitle", resourceCulture);
            }
        }
        
        public static string Debt_StudentLoans_SectionTitle {
            get {
                return ResourceManager.GetString("Debt_StudentLoans_SectionTitle", resourceCulture);
            }
        }
        
        public static string Debt_StudentLoans_Hint {
            get {
                return ResourceManager.GetString("Debt_StudentLoans_Hint", resourceCulture);
            }
        }
        
        public static string Debt_StudentLoans_Item {
            get {
                return ResourceManager.GetString("Debt_StudentLoans_Item", resourceCulture);
            }
        }
        
        public static string Debt_StudentLoans_AddItem {
            get {
                return ResourceManager.GetString("Debt_StudentLoans_AddItem", resourceCulture);
            }
        }
        
        public static string Debt_MedicalDebt_Title {
            get {
                return ResourceManager.GetString("Debt_MedicalDebt_Title", resourceCulture);
            }
        }
        
        public static string Debt_MedicalDebt_Subtitle {
            get {
                return ResourceManager.GetString("Debt_MedicalDebt_Subtitle", resourceCulture);
            }
        }
        
        public static string Debt_MedicalDebt_SectionTitle {
            get {
                return ResourceManager.GetString("Debt_MedicalDebt_SectionTitle", resourceCulture);
            }
        }
        
        public static string Debt_MedicalDebt_Hint {
            get {
                return ResourceManager.GetString("Debt_MedicalDebt_Hint", resourceCulture);
            }
        }
        
        public static string Debt_MedicalDebt_Item {
            get {
                return ResourceManager.GetString("Debt_MedicalDebt_Item", resourceCulture);
            }
        }
        
        public static string Debt_MedicalDebt_AddItem {
            get {
                return ResourceManager.GetString("Debt_MedicalDebt_AddItem", resourceCulture);
            }
        }
        
        public static string Debt_PersonalLoans_Title {
            get {
                return ResourceManager.GetString("Debt_PersonalLoans_Title", resourceCulture);
            }
        }
        
        public static string Debt_PersonalLoans_Subtitle {
            get {
                return ResourceManager.GetString("Debt_PersonalLoans_Subtitle", resourceCulture);
            }
        }
        
        public static string Debt_PersonalLoans_SectionTitle {
            get {
                return ResourceManager.GetString("Debt_PersonalLoans_SectionTitle", resourceCulture);
            }
        }
        
        public static string Debt_PersonalLoans_Hint {
            get {
                return ResourceManager.GetString("Debt_PersonalLoans_Hint", resourceCulture);
            }
        }
        
        public static string Debt_PersonalLoans_Item {
            get {
                return ResourceManager.GetString("Debt_PersonalLoans_Item", resourceCulture);
            }
        }
        
        public static string Debt_PersonalLoans_AddItem {
            get {
                return ResourceManager.GetString("Debt_PersonalLoans_AddItem", resourceCulture);
            }
        }
        
        public static string Debt_PersonalLoans_DebtType {
            get {
                return ResourceManager.GetString("Debt_PersonalLoans_DebtType", resourceCulture);
            }
        }
        
        public static string Debt_CreditCards_Title {
            get {
                return ResourceManager.GetString("Debt_CreditCards_Title", resourceCulture);
            }
        }
        
        public static string Debt_CreditCards_Subtitle {
            get {
                return ResourceManager.GetString("Debt_CreditCards_Subtitle", resourceCulture);
            }
        }
        
        public static string Debt_CreditCards_SectionTitle {
            get {
                return ResourceManager.GetString("Debt_CreditCards_SectionTitle", resourceCulture);
            }
        }
        
        public static string Debt_CreditCards_Hint {
            get {
                return ResourceManager.GetString("Debt_CreditCards_Hint", resourceCulture);
            }
        }
        
        public static string Debt_CreditCards_Item {
            get {
                return ResourceManager.GetString("Debt_CreditCards_Item", resourceCulture);
            }
        }
        
        public static string Debt_CreditCards_AddItem {
            get {
                return ResourceManager.GetString("Debt_CreditCards_AddItem", resourceCulture);
            }
        }
        
        public static string Debt_Field_Name {
            get {
                return ResourceManager.GetString("Debt_Field_Name", resourceCulture);
            }
        }
        
        public static string Debt_Field_Balance {
            get {
                return ResourceManager.GetString("Debt_Field_Balance", resourceCulture);
            }
        }
        
        public static string Debt_Field_InterestRate {
            get {
                return ResourceManager.GetString("Debt_Field_InterestRate", resourceCulture);
            }
        }
        
        public static string Debt_Field_Frequency {
            get {
                return ResourceManager.GetString("Debt_Field_Frequency", resourceCulture);
            }
        }
        
        public static string Debt_Field_TermInYears {
            get {
                return ResourceManager.GetString("Debt_Field_TermInYears", resourceCulture);
            }
        }
        
        public static string Debt_LinkedAsset {
            get {
                return ResourceManager.GetString("Debt_LinkedAsset", resourceCulture);
            }
        }
        
        public static string Debt_PrimaryResidence {
            get {
                return ResourceManager.GetString("Debt_PrimaryResidence", resourceCulture);
            }
        }
        
        public static string Debt_Standalone {
            get {
                return ResourceManager.GetString("Debt_Standalone", resourceCulture);
            }
        }
        
        public static string Debt_CarLoans_Title {
            get {
                return ResourceManager.GetString("Debt_CarLoans_Title", resourceCulture);
            }
        }
        
        public static string Debt_CarLoans_Subtitle {
            get {
                return ResourceManager.GetString("Debt_CarLoans_Subtitle", resourceCulture);
            }
        }
        
        public static string Debt_CarLoans_SectionTitle {
            get {
                return ResourceManager.GetString("Debt_CarLoans_SectionTitle", resourceCulture);
            }
        }
        
        public static string Debt_CarLoans_Hint {
            get {
                return ResourceManager.GetString("Debt_CarLoans_Hint", resourceCulture);
            }
        }
        
        public static string Debt_CarLoans_Item {
            get {
                return ResourceManager.GetString("Debt_CarLoans_Item", resourceCulture);
            }
        }
        
        public static string Debt_CarLoans_AddItem {
            get {
                return ResourceManager.GetString("Debt_CarLoans_AddItem", resourceCulture);
            }
        }
        
        public static string Debt_CarLoans_DefaultName {
            get {
                return ResourceManager.GetString("Debt_CarLoans_DefaultName", resourceCulture);
            }
        }
        
        public static string Spending_Next {
            get {
                return ResourceManager.GetString("Spending_Next", resourceCulture);
            }
        }
        
        public static string Spending_Remove {
            get {
                return ResourceManager.GetString("Spending_Remove", resourceCulture);
            }
        }
        
        public static string Spending_Field_Name {
            get {
                return ResourceManager.GetString("Spending_Field_Name", resourceCulture);
            }
        }
        
        public static string Spending_Field_Amount {
            get {
                return ResourceManager.GetString("Spending_Field_Amount", resourceCulture);
            }
        }
        
        public static string Spending_Field_Expense {
            get {
                return ResourceManager.GetString("Spending_Field_Expense", resourceCulture);
            }
        }
        
        public static string Spending_Field_Frequency {
            get {
                return ResourceManager.GetString("Spending_Field_Frequency", resourceCulture);
            }
        }
        
        public static string Spending_Living_Title {
            get {
                return ResourceManager.GetString("Spending_Living_Title", resourceCulture);
            }
        }
        
        public static string Spending_Living_Subtitle {
            get {
                return ResourceManager.GetString("Spending_Living_Subtitle", resourceCulture);
            }
        }
        
        public static string Spending_Living_SectionTitle {
            get {
                return ResourceManager.GetString("Spending_Living_SectionTitle", resourceCulture);
            }
        }
        
        public static string Spending_Living_RentOrMortgage {
            get {
                return ResourceManager.GetString("Spending_Living_RentOrMortgage", resourceCulture);
            }
        }
        
        public static string Spending_Living_Food {
            get {
                return ResourceManager.GetString("Spending_Living_Food", resourceCulture);
            }
        }
        
        public static string Spending_Living_Utilities {
            get {
                return ResourceManager.GetString("Spending_Living_Utilities", resourceCulture);
            }
        }
        
        public static string Spending_Living_Insurance {
            get {
                return ResourceManager.GetString("Spending_Living_Insurance", resourceCulture);
            }
        }
        
        public static string Spending_Living_Gas {
            get {
                return ResourceManager.GetString("Spending_Living_Gas", resourceCulture);
            }
        }
        
        public static string Spending_Living_HomeMaintenance {
            get {
                return ResourceManager.GetString("Spending_Living_HomeMaintenance", resourceCulture);
            }
        }
        
        public static string Spending_Living_Cellphone {
            get {
                return ResourceManager.GetString("Spending_Living_Cellphone", resourceCulture);
            }
        }
        
        public static string Spending_Living_HealthSpendings {
            get {
                return ResourceManager.GetString("Spending_Living_HealthSpendings", resourceCulture);
            }
        }
        
        public static string Spending_Living_OtherLivingExpenses {
            get {
                return ResourceManager.GetString("Spending_Living_OtherLivingExpenses", resourceCulture);
            }
        }
        
        public static string Spending_Discretionary_Title {
            get {
                return ResourceManager.GetString("Spending_Discretionary_Title", resourceCulture);
            }
        }
        
        public static string Spending_Discretionary_Subtitle {
            get {
                return ResourceManager.GetString("Spending_Discretionary_Subtitle", resourceCulture);
            }
        }
        
        public static string Spending_Discretionary_SectionTitle {
            get {
                return ResourceManager.GetString("Spending_Discretionary_SectionTitle", resourceCulture);
            }
        }
        
        public static string Spending_Discretionary_GymMembership {
            get {
                return ResourceManager.GetString("Spending_Discretionary_GymMembership", resourceCulture);
            }
        }
        
        public static string Spending_Discretionary_Subscriptions {
            get {
                return ResourceManager.GetString("Spending_Discretionary_Subscriptions", resourceCulture);
            }
        }
        
        public static string Spending_Discretionary_EatingOut {
            get {
                return ResourceManager.GetString("Spending_Discretionary_EatingOut", resourceCulture);
            }
        }
        
        public static string Spending_Discretionary_Entertainment {
            get {
                return ResourceManager.GetString("Spending_Discretionary_Entertainment", resourceCulture);
            }
        }
        
        public static string Spending_Discretionary_Travel {
            get {
                return ResourceManager.GetString("Spending_Discretionary_Travel", resourceCulture);
            }
        }
        
        public static string Spending_Discretionary_CharitableDonations {
            get {
                return ResourceManager.GetString("Spending_Discretionary_CharitableDonations", resourceCulture);
            }
        }
        
        public static string Spending_Discretionary_OtherDiscretionaryExpenses {
            get {
                return ResourceManager.GetString("Spending_Discretionary_OtherDiscretionaryExpenses", resourceCulture);
            }
        }
        
        public static string Spending_Discretionary_UseGroupedEntry {
            get {
                return ResourceManager.GetString("Spending_Discretionary_UseGroupedEntry", resourceCulture);
            }
        }
        
        public static string Spending_Discretionary_Detailed {
            get {
                return ResourceManager.GetString("Spending_Discretionary_Detailed", resourceCulture);
            }
        }
        
        public static string Spending_Discretionary_Grouped {
            get {
                return ResourceManager.GetString("Spending_Discretionary_Grouped", resourceCulture);
            }
        }
        
        public static string Spending_Discretionary_GroupedAmount {
            get {
                return ResourceManager.GetString("Spending_Discretionary_GroupedAmount", resourceCulture);
            }
        }
        
        public static string Spending_DebtRepayments_Title {
            get {
                return ResourceManager.GetString("Spending_DebtRepayments_Title", resourceCulture);
            }
        }
        
        public static string Spending_DebtRepayments_Subtitle {
            get {
                return ResourceManager.GetString("Spending_DebtRepayments_Subtitle", resourceCulture);
            }
        }
        
        public static string Spending_DebtRepayments_SectionTitle {
            get {
                return ResourceManager.GetString("Spending_DebtRepayments_SectionTitle", resourceCulture);
            }
        }
        
        public static string Spending_DebtRepayments_Hint {
            get {
                return ResourceManager.GetString("Spending_DebtRepayments_Hint", resourceCulture);
            }
        }
        
        public static string Spending_DebtRepayments_Item {
            get {
                return ResourceManager.GetString("Spending_DebtRepayments_Item", resourceCulture);
            }
        }
        
        public static string Spending_DebtRepayments_AddItem {
            get {
                return ResourceManager.GetString("Spending_DebtRepayments_AddItem", resourceCulture);
            }
        }
        
        public static string Spending_DebtRepayments_DefaultName {
            get {
                return ResourceManager.GetString("Spending_DebtRepayments_DefaultName", resourceCulture);
            }
        }
        
        public static string Spending_AssetsExpenses_Title {
            get {
                return ResourceManager.GetString("Spending_AssetsExpenses_Title", resourceCulture);
            }
        }
        
        public static string Spending_AssetsExpenses_Subtitle {
            get {
                return ResourceManager.GetString("Spending_AssetsExpenses_Subtitle", resourceCulture);
            }
        }
        
        public static string Spending_AssetsExpenses_SectionTitle {
            get {
                return ResourceManager.GetString("Spending_AssetsExpenses_SectionTitle", resourceCulture);
            }
        }
        
        public static string Spending_AssetsExpenses_Hint {
            get {
                return ResourceManager.GetString("Spending_AssetsExpenses_Hint", resourceCulture);
            }
        }
        
        public static string Spending_AssetsExpenses_Item {
            get {
                return ResourceManager.GetString("Spending_AssetsExpenses_Item", resourceCulture);
            }
        }
        
        public static string Spending_AssetsExpenses_AddItem {
            get {
                return ResourceManager.GetString("Spending_AssetsExpenses_AddItem", resourceCulture);
            }
        }
        
        public static string Spending_AssetsExpenses_DefaultName {
            get {
                return ResourceManager.GetString("Spending_AssetsExpenses_DefaultName", resourceCulture);
            }
        }
        
        public static string Spending_AssetsExpenses_Home {
            get {
                return ResourceManager.GetString("Spending_AssetsExpenses_Home", resourceCulture);
            }
        }
        
        public static string Spending_AssetsExpenses_InvestmentProperty {
            get {
                return ResourceManager.GetString("Spending_AssetsExpenses_InvestmentProperty", resourceCulture);
            }
        }
        
        public static string Spending_AssetsExpenses_InvestmentAccount {
            get {
                return ResourceManager.GetString("Spending_AssetsExpenses_InvestmentAccount", resourceCulture);
            }
        }
        
        public static string Spending_AssetsExpenses_PhysicalAsset {
            get {
                return ResourceManager.GetString("Spending_AssetsExpenses_PhysicalAsset", resourceCulture);
            }
        }
        
        public static string Spending_Other_Title {
            get {
                return ResourceManager.GetString("Spending_Other_Title", resourceCulture);
            }
        }
        
        public static string Spending_Other_Subtitle {
            get {
                return ResourceManager.GetString("Spending_Other_Subtitle", resourceCulture);
            }
        }
        
        public static string Spending_Other_SectionTitle {
            get {
                return ResourceManager.GetString("Spending_Other_SectionTitle", resourceCulture);
            }
        }
        
        public static string Spending_Other_Hint {
            get {
                return ResourceManager.GetString("Spending_Other_Hint", resourceCulture);
            }
        }
        
        public static string Spending_Other_Item {
            get {
                return ResourceManager.GetString("Spending_Other_Item", resourceCulture);
            }
        }
        
        public static string Spending_Other_AddItem {
            get {
                return ResourceManager.GetString("Spending_Other_AddItem", resourceCulture);
            }
        }
    }
}
