//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetirementTime.Resources.Dashboard {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DashboardResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DashboardResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("RetirementTime.Resources.Dashboard.DashboardResources", typeof(DashboardResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Home_Title {
            get {
                return ResourceManager.GetString("Home_Title", resourceCulture);
            }
        }
        
        public static string Home_Subtitle {
            get {
                return ResourceManager.GetString("Home_Subtitle", resourceCulture);
            }
        }
        
        public static string Home_Greeting {
            get {
                return ResourceManager.GetString("Home_Greeting", resourceCulture);
            }
        }
        
        public static string Home_Description {
            get {
                return ResourceManager.GetString("Home_Description", resourceCulture);
            }
        }
        
        public static string Home_Logout {
            get {
                return ResourceManager.GetString("Home_Logout", resourceCulture);
            }
        }
        
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        public static string Settings_IntroSection {
            get {
                return ResourceManager.GetString("Settings_IntroSection", resourceCulture);
            }
        }
        
        public static string Settings_ResetIntroLabel {
            get {
                return ResourceManager.GetString("Settings_ResetIntroLabel", resourceCulture);
            }
        }
        
        public static string Settings_ResetIntroDescription {
            get {
                return ResourceManager.GetString("Settings_ResetIntroDescription", resourceCulture);
            }
        }
        
        public static string Settings_ResetIntroButton {
            get {
                return ResourceManager.GetString("Settings_ResetIntroButton", resourceCulture);
            }
        }
    }
}
