//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetirementTime.Resources.Landing {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LandingResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LandingResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("RetirementTime.Resources.Landing.LandingResources", typeof(LandingResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Home_PlanningTools {
            get {
                return ResourceManager.GetString("Home_PlanningTools", resourceCulture);
            }
        }
        
        public static string Home_About {
            get {
                return ResourceManager.GetString("Home_About", resourceCulture);
            }
        }
        
        public static string Home_Contact {
            get {
                return ResourceManager.GetString("Home_Contact", resourceCulture);
            }
        }
        
        public static string Home_StartPlanning {
            get {
                return ResourceManager.GetString("Home_StartPlanning", resourceCulture);
            }
        }
        
        public static string Home_Login {
            get {
                return ResourceManager.GetString("Home_Login", resourceCulture);
            }
        }
        
        public static string Home_HeroTitle {
            get {
                return ResourceManager.GetString("Home_HeroTitle", resourceCulture);
            }
        }
        
        public static string Home_HeroSubtitle {
            get {
                return ResourceManager.GetString("Home_HeroSubtitle", resourceCulture);
            }
        }
        
        public static string Home_StatusOnTrack {
            get {
                return ResourceManager.GetString("Home_StatusOnTrack", resourceCulture);
            }
        }
        
        public static string Home_YearsToRetirement {
            get {
                return ResourceManager.GetString("Home_YearsToRetirement", resourceCulture);
            }
        }
        
        public static string Home_SavingsProjected {
            get {
                return ResourceManager.GetString("Home_SavingsProjected", resourceCulture);
            }
        }
        
        public static string Home_MortgagePaid {
            get {
                return ResourceManager.GetString("Home_MortgagePaid", resourceCulture);
            }
        }
        
        public static string Home_TravelFund {
            get {
                return ResourceManager.GetString("Home_TravelFund", resourceCulture);
            }
        }
        
        public static string Home_EmergencyFund {
            get {
                return ResourceManager.GetString("Home_EmergencyFund", resourceCulture);
            }
        }
        
        public static string Home_ComprehensivePlanningTitle {
            get {
                return ResourceManager.GetString("Home_ComprehensivePlanningTitle", resourceCulture);
            }
        }
        
        public static string Home_ComprehensivePlanningSubtitle {
            get {
                return ResourceManager.GetString("Home_ComprehensivePlanningSubtitle", resourceCulture);
            }
        }
        
        public static string Home_GoalBasedTitle {
            get {
                return ResourceManager.GetString("Home_GoalBasedTitle", resourceCulture);
            }
        }
        
        public static string Home_GoalBasedSubtitle {
            get {
                return ResourceManager.GetString("Home_GoalBasedSubtitle", resourceCulture);
            }
        }
        
        public static string Home_InvestmentGrowthTitle {
            get {
                return ResourceManager.GetString("Home_InvestmentGrowthTitle", resourceCulture);
            }
        }
        
        public static string Home_InvestmentGrowthSubtitle {
            get {
                return ResourceManager.GetString("Home_InvestmentGrowthSubtitle", resourceCulture);
            }
        }
        
        public static string Home_AverageGoalNumber {
            get {
                return ResourceManager.GetString("Home_AverageGoalNumber", resourceCulture);
            }
        }
        
        public static string Home_AverageGoalLabel {
            get {
                return ResourceManager.GetString("Home_AverageGoalLabel", resourceCulture);
            }
        }
        
        public static string Home_ExperienceNumber {
            get {
                return ResourceManager.GetString("Home_ExperienceNumber", resourceCulture);
            }
        }
        
        public static string Home_ExperienceLabel {
            get {
                return ResourceManager.GetString("Home_ExperienceLabel", resourceCulture);
            }
        }
        
        public static string Home_Resources {
            get {
                return ResourceManager.GetString("Home_Resources", resourceCulture);
            }
        }
    }
}
