//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetirementTime.Resources.Landing {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LandingResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LandingResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RetirementTime.Resources.Landing.LandingResources", typeof(LandingResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT.
        /// </summary>
        public static string Home_About {
            get {
                return ResourceManager.GetString("Home_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Retirement Goal.
        /// </summary>
        public static string Home_AverageGoalLabel {
            get {
                return ResourceManager.GetString("Home_AverageGoalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $1M+.
        /// </summary>
        public static string Home_AverageGoalNumber {
            get {
                return ResourceManager.GetString("Home_AverageGoalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retirement Calculator &amp; Tools.
        /// </summary>
        public static string Home_ComprehensivePlanningSubtitle {
            get {
                return ResourceManager.GetString("Home_ComprehensivePlanningSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprehensive Planning.
        /// </summary>
        public static string Home_ComprehensivePlanningTitle {
            get {
                return ResourceManager.GetString("Home_ComprehensivePlanningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTACT.
        /// </summary>
        public static string Home_Contact {
            get {
                return ResourceManager.GetString("Home_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💰 Emergency Fund.
        /// </summary>
        public static string Home_EmergencyFund {
            get {
                return ResourceManager.GetString("Home_EmergencyFund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years of Planning Experience.
        /// </summary>
        public static string Home_ExperienceLabel {
            get {
                return ResourceManager.GetString("Home_ExperienceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30+.
        /// </summary>
        public static string Home_ExperienceNumber {
            get {
                return ResourceManager.GetString("Home_ExperienceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalized Strategies.
        /// </summary>
        public static string Home_GoalBasedSubtitle {
            get {
                return ResourceManager.GetString("Home_GoalBasedSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal-Based Approach.
        /// </summary>
        public static string Home_GoalBasedTitle {
            get {
                return ResourceManager.GetString("Home_GoalBasedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy-to-understand tools and guidance for your retirement journey.
        /// </summary>
        public static string Home_HeroSubtitle {
            get {
                return ResourceManager.GetString("Home_HeroSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock Your Financial Future With Simple Retirement Planning.
        /// </summary>
        public static string Home_HeroTitle {
            get {
                return ResourceManager.GetString("Home_HeroTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compound Interest Calculator.
        /// </summary>
        public static string Home_InvestmentGrowthSubtitle {
            get {
                return ResourceManager.GetString("Home_InvestmentGrowthSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investment Growth.
        /// </summary>
        public static string Home_InvestmentGrowthTitle {
            get {
                return ResourceManager.GetString("Home_InvestmentGrowthTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        public static string Home_Login {
            get {
                return ResourceManager.GetString("Home_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🏠 Mortgage Paid.
        /// </summary>
        public static string Home_MortgagePaid {
            get {
                return ResourceManager.GetString("Home_MortgagePaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLANNING TOOLS.
        /// </summary>
        public static string Home_PlanningTools {
            get {
                return ResourceManager.GetString("Home_PlanningTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESOURCES.
        /// </summary>
        public static string Home_Resources {
            get {
                return ResourceManager.GetString("Home_Resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $485,000 Projected.
        /// </summary>
        public static string Home_SavingsProjected {
            get {
                return ResourceManager.GetString("Home_SavingsProjected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START PLANNING.
        /// </summary>
        public static string Home_StartPlanning {
            get {
                return ResourceManager.GetString("Home_StartPlanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ON TRACK ✓.
        /// </summary>
        public static string Home_StatusOnTrack {
            get {
                return ResourceManager.GetString("Home_StatusOnTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✈️ Travel Fund.
        /// </summary>
        public static string Home_TravelFund {
            get {
                return ResourceManager.GetString("Home_TravelFund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12 Years to Retirement.
        /// </summary>
        public static string Home_YearsToRetirement {
            get {
                return ResourceManager.GetString("Home_YearsToRetirement", resourceCulture);
            }
        }
    }
}
