//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetirementTime.Resources.Auth {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AuthResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AuthResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("RetirementTime.Resources.Auth.AuthResources", typeof(AuthResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Login_WelcomeBack {
            get {
                return ResourceManager.GetString("Login_WelcomeBack", resourceCulture);
            }
        }
        
        public static string Login_Subtitle {
            get {
                return ResourceManager.GetString("Login_Subtitle", resourceCulture);
            }
        }
        
        public static string Login_Email {
            get {
                return ResourceManager.GetString("Login_Email", resourceCulture);
            }
        }
        
        public static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        public static string Login_RememberMe {
            get {
                return ResourceManager.GetString("Login_RememberMe", resourceCulture);
            }
        }
        
        public static string Login_ForgotPassword {
            get {
                return ResourceManager.GetString("Login_ForgotPassword", resourceCulture);
            }
        }
        
        public static string Login_LoginButton {
            get {
                return ResourceManager.GetString("Login_LoginButton", resourceCulture);
            }
        }
        
        public static string Login_OrContinueWith {
            get {
                return ResourceManager.GetString("Login_OrContinueWith", resourceCulture);
            }
        }
        
        public static string Login_GoogleSignIn {
            get {
                return ResourceManager.GetString("Login_GoogleSignIn", resourceCulture);
            }
        }
        
        public static string Login_NoAccount {
            get {
                return ResourceManager.GetString("Login_NoAccount", resourceCulture);
            }
        }
        
        public static string Login_SignUpLink {
            get {
                return ResourceManager.GetString("Login_SignUpLink", resourceCulture);
            }
        }
        
        public static string SignUp_CreateAccount {
            get {
                return ResourceManager.GetString("SignUp_CreateAccount", resourceCulture);
            }
        }
        
        public static string SignUp_Subtitle {
            get {
                return ResourceManager.GetString("SignUp_Subtitle", resourceCulture);
            }
        }
        
        public static string SignUp_FirstName {
            get {
                return ResourceManager.GetString("SignUp_FirstName", resourceCulture);
            }
        }
        
        public static string SignUp_LastName {
            get {
                return ResourceManager.GetString("SignUp_LastName", resourceCulture);
            }
        }
        
        public static string SignUp_Email {
            get {
                return ResourceManager.GetString("SignUp_Email", resourceCulture);
            }
        }
        
        public static string SignUp_Password {
            get {
                return ResourceManager.GetString("SignUp_Password", resourceCulture);
            }
        }
        
        public static string SignUp_ConfirmPassword {
            get {
                return ResourceManager.GetString("SignUp_ConfirmPassword", resourceCulture);
            }
        }
        
        public static string SignUp_Country {
            get {
                return ResourceManager.GetString("SignUp_Country", resourceCulture);
            }
        }
        
        public static string SignUp_SelectCountry {
            get {
                return ResourceManager.GetString("SignUp_SelectCountry", resourceCulture);
            }
        }
        
        public static string SignUp_State {
            get {
                return ResourceManager.GetString("SignUp_State", resourceCulture);
            }
        }
        
        public static string SignUp_SelectState {
            get {
                return ResourceManager.GetString("SignUp_SelectState", resourceCulture);
            }
        }
        
        public static string SignUp_CreateAccountButton {
            get {
                return ResourceManager.GetString("SignUp_CreateAccountButton", resourceCulture);
            }
        }
        
        public static string SignUp_HaveAccount {
            get {
                return ResourceManager.GetString("SignUp_HaveAccount", resourceCulture);
            }
        }
        
        public static string SignUp_LoginLink {
            get {
                return ResourceManager.GetString("SignUp_LoginLink", resourceCulture);
            }
        }
    }
}
